### ISSUE TITLE
is it possible to not use the render function from clndr?

### ISSUE THREAD

**Issue by rp6** [kylestetz/CLNDR#107]
In angular it would be possible to set some javascript objects and a function would recognize that and render some stuff by its own. I know the angularjs directive from your doku but it doesn't work for me. Maybe its possible to set the render function to something that doesn't do anything?

**Comment by nsbabrah** [comment]
Uncaught TypeError: $(...).clndr is not a function    . I have this error while working with clndr.js and its show me clndr but  without styling .

**Comment by nsbabrah** [comment]
Uncaught Error: CLNDR cannot be instantiated on an empty selector. this other erro I do had all the time.

**Comment by hopeseekr** [comment]
Using
```
$(function() {
    $("#calendar").clndr();
});

<div id="calendar"></div>
```

I get

> jquery-3.5.1.min.js:2 Uncaught Error: CLNDR cannot be instantiated on an empty selector.

I'm assuming it's not compatible with jQuery 3?

**Comment by mikegioia** [comment]
That's a good question @hopeseekr. Our production app that uses CLNDR is running 3.5.1 and CLNDR without any issues, but I don't think the tests here have been tested against v3.

I have run this locally with jQuery 3.5 and that same command you've run and it does work for me (fyi). If you are able to put a working fiddle or example together of it failing would you mind submitting that as a new issue?
