### ISSUE TITLE
Any way to show a week view only?

### ISSUE THREAD

**Issue by sylouuu** [kylestetz/CLNDR#13]
Amazing job you have done!

I would like to ask you if is it already possible to show a week only, not a full month?

Regards :)

**EDIT**: And the anwser is:

**Template**    

``` html
<script type="text/template" id="clndr_template">
    <div class="controls">
        <button class="clndr-previous-button">Prev.</button>
        <div class="month"><%= days[extras.currentWeek * 7].date.format('YYYY-MM-DD') %> - <%= days[extras.currentWeek * 7 + 6].date.format('YYYY-MM-DD') %></div>
        <button class="clndr-next-button">Next</button>
    </div>

    <div class="days-of-the-week clearfix">
        <% _.each(daysOfTheWeek, function(day) { %>
            <div class="header-day"><%= day %></div>
        <% }); %>
    </div>

    <div class="days clearfix">
        <% for(var i = extras.currentWeek * 7; i < extras.currentWeek * 7 + 7; i++) { %>
            <div class="<%= days[i].classes %>" id="<%= days[i].id %>"><%= days[i].day %></div>
        <% } %>
    </div>
</script>

<div id="clndr"></div>
```

**Javascript**

``` javascript
function weeksInMonth(month) {
    return Math.floor((month.daysInMonth() + moment(month).startOf('month').weekday()) / 7);
}

var clndr = $('#clndr').clndr({
    template: $('#clndr_template').html(),
    extras: {
        currentWeek: Math.floor( ( ( (moment().date() + moment().startOf('month').weekday() ) - 1 ) / ( weeksInMonth(moment() ) * 7) ) * weeksInMonth( moment() ) )
    },
    doneRendering: function() {

        /* Next button handler */
        $('#clndr .clndr-next-button').on('click', function() {

            /* Get numbers of weeks in the month */
            var weeks_in_month = Math.floor(clndr.month.daysInMonth() / 7) - 1;

            if(clndr.options.extras.currentWeek < weeks_in_month) {
                /* Increase the week count */
                clndr.options.extras.currentWeek += 1;
            } else {
                /* Reset the week count */
                clndr.options.extras.currentWeek = 0;

                /* Go to next month */
                clndr.next();
            }

            clndr.render();
        });

        /* Previous button handler */
        $('#clndr .clndr-previous-button').on('click', function() {

            /* Get numbers of weeks in the month */
            var weeks_in_month = Math.floor(clndr.month.weeks_in_month() / 7) - 1;

            if(clndr.options.extras.currentWeek > 0) {
                /* Decrease the week count */
                clndr.options.extras.currentWeek -= 1;
            } else {
                /* Reset the week count */
                clndr.options.extras.currentWeek = weeks_in_month;

                /* Go to previous month */
                clndr.back();
            }

            clndr.render();
        });

    }
});
```

**Comment by anindyakm** [comment]
I am facing issue with the previous and next. Please find the my code below

 clndrData  = $chooseDate.clndr({
                  //  template: $('script#bookMeClndrTemplate').html(),
                    template: $('script#clndr_template').html(),
                    constraints: {
                        startDate: currentDate.format('YYYY-MM-DD')
                    },
                    ignoreInactiveDaysInSelection: true,
                    trackSelectedDate: true,
                    showAdjacentMonths: true,
                    ready: function () {
                        if (_.isNull(slotsData)) {
                            self.updateAvailableDays(currentDate, pkg, self, this, true);
                        } else {
                            self.onMonthSlotsGetSuccess(slotsData, currentDate, pkg, this, monthsAhead);
                        }
                    },
                    clickEvents: {
                       click: function (target) {
                            if (!$(target.element).hasClass('inactive') && !$(target.element).hasClass('empty')) {
                                self.updateSelectedDate(target.date, pkg, self, this);
                                //$chooseDate.hide();
                                //$('#' + self.breakpoint + '-choose-time-' + pkg.id).show();
                            }
                        },
                        onMonthChange(momentObj) {
                            this.options.extras.availableSlots = [];
                            this.render();
                            //var selfCalender=this;
                            //selfCalender.month=momentObj.month();
                            if (currentDate.year() === momentObj.year() && currentDate.month() === momentObj.month()) {
                                momentObj = currentDate;
                            }
                            //self.updateAvailableDays(momentObj, pkg, self, this, false);
                        }
                    },
                    extras: {
                        availableSlots: [],
                        currentWeek: Math.floor( ( ( (moment().date() + moment().startOf('month').weekday() ) - 1 ) / ( self.weeksInMonth(moment() ) * 7) ) * self.weeksInMonth( moment() ) )
                    },
                    doneRendering: function() {

                    var selfCalender=this;

                    console.log(selfCalender.month)
                    console.log(selfCalender.month.weeks_in_month)

                    /* Next button handler */
                            $('.book-me-week-calender .clndr-next-button').on('click', function() {



                                /* Get numbers of weeks in the month */
                               /* var weeks_in_month = Math.floor(selfCalender.month.daysInMonth() / 7) - 1;
                            
                                if(selfCalender.options.extras.currentWeek < weeks_in_month) {
                                    /* Increase the week count */
                                    selfCalender.options.extras.currentWeek += 1;
                                } else {
                                    /* Reset the week count */
                                    selfCalender.options.extras.currentWeek = 0;

                                    /* Go to next month */
                                    selfCalender.next();
                                }

                                selfCalender.render();*/


                                 /* Get numbers of weeks in the month */
                                var weeks_in_month = self.weeksInMonth(selfCalender.month) - 1;

                                if(selfCalender.options.extras.currentWeek < weeks_in_month) {
                                    /* Increase the week count */
                                    selfCalender.options.extras.currentWeek += 1;
                                    selfCalender.render();
                                } else if(selfCalender.options.extras.currentWeek > weeks_in_month) {
                                    /* If we started at the last week of the month, we want to skip over currentWeek = 0 */
                                    selfCalender.options.extras.currentWeek = 1;
                                    selfCalender.next();
                                } else {
                                    /* Reset the week count */
                                    selfCalender.options.extras.currentWeek = 0;

                                    /* Go to next month */
                                    selfCalender.next();
                                }

                            });

                            /* Previous button handler */
                            $('.book-me-week-calender .clndr-previous-button').on('click', function() {

                                /* Get numbers of weeks in the month */
                                /*var weeks_in_month = Math.floor(selfCalender.month.weeks_in_month() / 7) - 1;

                        
                                if(selfCalender.options.extras.currentWeek > 0) {
                                    /* Decrease the week count */
                                    selfCalender.options.extras.currentWeek -= 1;
                                } else {
                                    /* Reset the week count */
                                    selfCalender.options.extras.currentWeek = weeks_in_month;

                                    /* Go to previous month */
                                    selfCalender.back();
                                }

                                selfCalender.render();*/


                                 if(selfCalender.options.extras.currentWeek > 0) {
                                        /* Decrease the week count */
                                        selfCalender.options.extras.currentWeek -= 1;
                                        selfCalender.render();
                                    }
                                    /* however if we've crossed 0, we need weeks_in_month to reflect LAST month
                                       before clndr has had a chance to go back. */
                                    else {
                                        var weeks_in_month = self.weeksInMonth( moment(selfCalender.month).subtract('month', 1) ) - 1;
                                        /* Reset the week count */
                                        selfCalender.options.extras.currentWeek = weeks_in_month;

                                        /* Go to previous month */
                                        selfCalender.back();
                                    }
                            });
                    }
                });
For the next month it shows the invalid date and for the previous month it gives __"TypeError: selfCalender.month.weeks_in_month is not a function"__

**Comment by anindyakm** [comment]
I got error when month change when month is change

var $chooseDate = $('#' + this.breakpoint + '-book-me-calendar');
                currentDate = _.isNull(currentDate) ? moment.tz(this.selected_timezone).startOf('day') : currentDate;

                self.calenderScript = $chooseDate.clndr({
                  //  template: $('script#bookMeClndrTemplate').html(),
                    template: $('script#clndr_template').html(),
                    constraints: {
                        startDate: currentDate.format('YYYY-MM-DD')
                    },
                    ignoreInactiveDaysInSelection: true,
                    trackSelectedDate: true,
                    showAdjacentMonths: true,
                    ready: function () {
                        
                    },
                    clickEvents: {
                        click: function (target) {
                           
                            }
                        },
                        onMonthChange(momentObj) {

                            
                        }
                    },
                    extras: {
                        availableSlots: [],
                        currentWeek: Math.floor( ( ( (moment().date() + moment().startOf('month').weekday() ) - 1 ) / ( self.weeksInMonth(moment() ) * 7) ) * self.weeksInMonth( moment() ) )
                    },
                    doneRendering: function() {



                            var selfCalender=this;

                            /* Next button handler */
                            $('.book-me-week-calender .clndr-next-button').on('click', function() {


                                /* Get numbers of weeks in the month */
                                var weeks_in_month = Math.floor(self.calenderScript.month.daysInMonth() / 7) + 1;

                                if(self.calenderScript.options.extras.currentWeek < weeks_in_month) {
                                    /* Increase the week count */
                                    self.calenderScript.options.extras.currentWeek += 1;
                                } else {
                                    /* Reset the week count */
                                    self.calenderScript.options.extras.currentWeek = 0;

                                    /* Go to next month */
                                     self.calenderScript.next();
                                }

                                self.calenderScript.render();

                                self.showTimeSlot = false;

                                console.log("next",self.calenderScript.month.daysInMonth());

                                console.log("next",self.calenderScript.options);


                            });

                            /* Previous button handler */
                            $('.book-me-week-calender .clndr-previous-button').on('click', function() {

                                /* Get numbers of weeks in the month */
                                var weeks_in_month = Math.floor(self.calenderScript.month.daysInMonth() / 7) + 1;


                                if(self.calenderScript.options.extras.currentWeek > 0) {
                                    /* Decrease the week count */
                                    self.calenderScript.options.extras.currentWeek -= 1;
                                } else {
                                    /* Reset the week count */
                                    self.calenderScript.options.extras.currentWeek = weeks_in_month;

                                    /* Go to previous month */
                                    self.calenderScript.back();
                                }

                                self.calenderScript.render();

                            });

                     


                    }
                });


Please help me.I need to fix this by today.

**Comment by Nitish4561** [comment]
Hi @kylestetz , thanks for providing the week view, is there any way out, where we could provide the "day" view?
