### ISSUE TITLE
Set date on instance of CLNDR

### ISSUE THREAD

**Issue by sn0lan** [kylestetz/CLNDR#133]
In the current version you have got:

theCalendarInstance.setMonth();
theCalendarInstance.setYear();

On a project Im working on, I need to essentially do CalendarInstance.setDate(moment) or CalendarInstance.setTodayAs(moment);

I have 2 calendars beside each other (arrival and depart) and I want them to play off each other. Allowing me to stop people using dates after the arrival and also being able to set the active state on the current day to the day after the one selected in arrival.

**Comment by kylestetz** [comment]
Closing this, feel free to open it back up if you're still looking for a solution.

**Comment by trottera** [comment]
i'd also be interessted in an setSelectedDate function, could this issue be reopened?

From what i can tell, right now you can set a selected date by setting a date to clndrInstance.options.selectesDate, then rerender the calendar and setting the month and year. I think to have these steps in one function would come in really handy.

Also, a resetSelectedDate function would be good. Or maybe this could be achieved with setSelectedDate(null).
