### ISSUE TITLE
Multiday Events issue

### ISSUE THREAD

**Issue by lesaff** [kylestetz/CLNDR#134]
Kyle, is it possible to default the endDate to be the same as the startDate if endDate is null?
That would solve the issue with mixing single and multiple day event.

**Comment by kylestetz** [comment]
I've been going back and forth on this one in my mind and I think I am finally coming around to it. Sorry for the very long, very silent stretch there.

**Comment by kylestetz** [comment]
My hesitation has been that multiday events are going to have `start` and `end` kind of properties, but there is ambiguity around whether or not a single day event would have `start` or `end` and not `date`. However, if you're creating an events system and for some reason putting the date in `start` but not `end` signifies a single-day event, this will work for you.

**Comment by kylestetz** [comment]
This has been implemented, along with a new `multiDayEvents.singleDay` configuration that allows you to explicitly mix single- and multi-day events.

**Comment by lesaff** [comment]
Thanks, sorry for the late reply. Really appreciate what you've done here.
