### ISSUE TITLE
Feature: multiple constraints interval

### ISSUE THREAD

**Issue by asprega** [kylestetz/CLNDR#139]
About the `constraints` feature, one thing that I would find very useful is the ability to provide multiple date intervals instead of just one. Is this a reasonable request?

**Comment by kylestetz** [comment]
I'm assuming you worked out a solution to this so I'm closing the issue. Feel free to open it again if you still have questions.

**Comment by asprega** [comment]
Oh yes, sorry I didn't get back to you. I eventually opted for dummy events as suggested. Thanks!
