### ISSUE TITLE
lazy loading / dynamically changing days array

### ISSUE THREAD

**Issue by kimda90** [kylestetz/CLNDR#141]
Hello, 

I'm trying to implement a lazy loading for a week view, by having a scrolleable div with 21 days, and only 7 visible, alert me when the view is near the start or the end of the scroll.

Is there a way to append new days (before or after) in the days array of the clndr object?

Thanks for all.

**Comment by kylestetz** [comment]
Unfortunately clndr isn't built this way— calling `render` destroys any previous markup you had.

The only way I can think of to explore this would be to have a clndr instance hiding somewhere on the page, controlled via the API, and grabbing the markup output from it after it renders using the `doneRendering` callback. That would allow you to lazily render other months and append them to the actual view.

Did that make any sense?

**Comment by kylestetz** [comment]
Closing this, feel free to open it back up if you have any other questions or thoughts.
