### ISSUE TITLE
Out of place comment?

### ISSUE THREAD

**Issue by webteckie** [kylestetz/CLNDR#142]
In the readme overview there's the following -- I think the first two lines do not belong?

  // show the numbers of days in months adjacent to the current month
  // (and populate them with their events). defaults to true.
  // CLNDR can accept events lasting more than one day!
  // just pass in the multiDayEvents option and specify what the start and
  // end fields are called within your event objects. See the example file
  // for a working instance of this.
  multiDayEvents: {
    startDate: 'startDate',
    endDate: 'endDate'
  },

**Comment by kylestetz** [comment]
I was confused for a bit until I realized you were in the intervals branch! Thanks.
