### ISSUE TITLE
Dates are not appearing on the correct days, just the current day only.

### ISSUE THREAD

**Issue by ayyobro** [kylestetz/CLNDR#143]
Was using your dates for testing on first build:

  var currentMonth = moment().format('YYYY-MM');
  var nextMonth    = moment().add('month', 1).format('YYYY-MM');

  var eventArray = [
    { date: currentMonth + '-' + '10', title: 'Persian Kitten Auction', location: 'Center for Beautiful Cats' },
    { date: currentMonth + '-' + '19', title: 'Cat Frisbee', location: 'Jefferson Park' },
    { date: currentMonth + '-' + '23', title: 'Kitten Demonstration', location: 'Center for Beautiful Cats' },
    { date: nextMonth + '-' + '07',    title: 'Small Cat Photo Session', location: 'Center for Cat Photography' }
  ];

Included dates like so: 'events: eventArray,'

But when I use the click event to view the events on each day, they do not appear in the console. I saw that my current day was highlighted because of my css, so I clicked that, then appeared the list of events underneath the current day even though they clearly had different dates set. 

Thoughts?

**Comment by kylestetz** [comment]
Ok, the demo that comes with the repo is working fine for me in Chrome and Firefox on OSX.

Are you saying that you _do_ see a console log, but that the event dates are wrong? Or are you not seeing a console log at all?

The demo has this bit of code in clndr's setup:
```javascript
$('#myCalendar').clndr({
  // some setup ...
  clickEvents: {
    click: function(target) {
      console.log(target);
    }
  }
  // ... some more setup
});
```

Do you have that? It sounds like clndr is working fine since you are seeing the visual result correctly.

**Comment by ayyobro** [comment]
I do see a console log coming through, yes. It was just only working when I clicked today's date and it showed all dates regardless of specified date string. I did end up fixing this because I noticed that when I had copied some of your examples over there was a multiday events parameter filled. Once I took this away the events went to their respective days. 

Thanks!
