### ISSUE TITLE
Calendar days show in wrong order when moment locale is changed

### ISSUE THREAD

**Issue by smohadjer** [kylestetz/CLNDR#144]
I have a calendar with a six-day week (not rendering Sundays) where week starts on Monday and all is good as you see here:
http://sandbox.saeidmohadjer.com/app/calendar_handlebars.html?locale=en

However when I set moment.js's locale to "de" to render the calendar in German the days show in a wrong order (offset by one day) as you see here:
http://sandbox.saeidmohadjer.com/app/calendar_handlebars.html?locale=de

Any idea what I'm doing wrong? All js is in HTML source code...

**Comment by smohadjer** [comment]
I stopped using clndr.js' "daysOfTheWeek" and "weekOffset" and instead used moment's isoWeekday() method (in combination with moment locale). This fixed the problem!

**Comment by kylestetz** [comment]
Sorry for not responding sooner— glad you were able to figure it out!

In case anyone else gets stuck on this one: each language configuration in moment.js decides which day of the week comes first— Sunday or Monday— so if you don't configure anything in clndr it will use moment's settings. `daysOfTheWeek` and `weekOffset` are fine if you know you're only ever dealing with one language, but it gets tricky when you are juggling multiple languages (as you've discovered).

If you _do_ need to use those two parameters, you might benefit from checking moment's language settings first and passing in the appropriate parameters to your clndr configuration.

**Comment by smohadjer** [comment]
Perhaps it won't be a bad idea to put your comment "daysOfTheWeek and weekOffset are fine if you know you're only ever dealing with one language" as a warning above those parameters in the doc. They pushed me in the wrong direction and it took me a while to figure out that using moment's locale is the right solution for language customizations. I think most users would try to use them as first choice when countering localization issues.

**Comment by kylestetz** [comment]
Thanks for the suggestion @smohadjer... It is covered in the [Internationalization](https://github.com/kylestetz/CLNDR#internationalization) section, but I realize that it's kind of buried and I'll make reference to it up top in the Usage section.

Cheers!

**Comment by smohadjer** [comment]
This line in doc above "daysOfTheWeek" was the one that threw me off the right path:
// (use in conjunction with weekOffset to change the starting day to Monday)

The only reason I can think of that someone wants to change starting day to Monday is localization, in that case using moment's isoWeekday() is a far better choice.

**Comment by kylestetz** [comment]
Got it, thanks for clarifying!

**Comment by smohadjer** [comment]
Btw, I searched for a donate button on your site, but didn't find any!

**Comment by kylestetz** [comment]
I'm not taking any, but I appreciate the thought :grin:

**Comment by Pinguwien** [comment]
Thank you guys, this thread just helped me out :) 
For me, it was the weekoffset of clndr (older version 1.2.0 atm), which was actually set to 'Monday', but instead just started on Sunday. After removing this option from my clndr-config, it all worked out well :)

**Comment by Vitaly9354** [comment]
Thanks! Helped me out 👍 
However it is a bit strange, yesterday my dates were fine. Today they have shifted for some reason so I applied weekOffset.
