### ISSUE TITLE
annual event

### ISSUE THREAD

**Issue by ileska** [kylestetz/CLNDR#147]
Hello! You made a great plugin! There is one thing i want to ask. Is it possible to add annual event, like birthday reminder? I would not want to add a variety of events each year.

**Comment by kylestetz** [comment]
Hey, thanks! Clndr does not support recurring events— the philosophy is that clndr is for _viewing_ your events, not _modifying_ them.

This has been discussed before in issues #70 and #118. Closing this issue, but feel free to ask any clarifying questions.
