### ISSUE TITLE
CLNDR renders 1 day offset

### ISSUE THREAD

**Issue by friedemannsommer** [kylestetz/CLNDR#149]
If i change the locale of momentjs, CLNDR renders every date with 1 day offset.

Tested with following Code (in Google Chrome 40.0.2214.93):

```javascript
moment.locale("de");

calendars.asEventCalendar = $('#asec-calendar').clndr(
    {
        multiDayEvents         : {
            startDate: 'startDate',
            endDate  : 'endDate',
            singleDay: 'date'
        },
        daysOfTheWeek          : moment.weekdays(),
        weekOffset             : 1,
        adjacentDaysChangeMonth: true,
        forceSixRows           : true,
        render                 : function(data) {
            currentEvents = data.eventsThisMonth;
            return calendarTemplate(data);
        },
        clickEvents            : {
            onMonthChange: function(month) {
                asec.view.eventList(currentEvents);
            }
        }
    }
);
```

**Comment by kylestetz** [comment]
Yep, this is because you are setting the `weekOffset` field to `1`. If you are in _english_ this is probably what you want, since you are trying to get the weeks to begin on Monday. But moment's `de` language setting starts the week off on Monday _already_, meaning that your `weekOffset` shifts it from Monday to Tuesday.

This is only an issue because moment.js's language settings declare which day the week begins on, and it's different between languages. If you had to you could set the configuration up depending on the language:

```javascript
// assuming we have a `currentLanguage` variable set to "en", "de", etc.
daysOfTheWeek: (currentLanguage === 'en') ? 1 : 0,
```

**Comment by friedemannsommer** [comment]
I still have that issue with following code.

```javascript
moment.locale('de');

$('#my-cool-calendar').clndr(
    {
        render                 : template,
        startWithMonth         : moment(),
        clickEvents            : {
            onMonthChange: function(month) {
                console.log(month);
            }
        },
        multiDayEvents         : {
            startDate: 'dateFrom',
            endDate  : 'dateTo',
            singleDay: 'date'
        },
        weekOffset             : 1,
        daysOfTheWeek          : moment.weekdays(),
        showAdjacentMonths     : true,
        adjacentDaysChangeMonth: true,
        events                 : events
    }
);
```

If i set ```moment``` to German locale CLNDR renders a offset of -1 day.
```javascript
moment.locale('de')
```
![clndr-with-issue-2](https://cloud.githubusercontent.com/assets/5468809/6170184/f93b811a-b2d2-11e4-832d-bb1ae00753bb.png)

```javascript
moment.locale('en')
```
![clndr-without-issue](https://cloud.githubusercontent.com/assets/5468809/6170183/f93ac0fe-b2d2-11e4-875c-2cd0049fddfa.png)

**Comment by friedemannsommer** [comment]
The solution for this issue is simple:

```javascript
// thats need because moment returns wrong formatted array
var weekdays = moment.weekdays();
weekdays.push(weekdays.shift());

$('#my-awesome-calendar').clndr(
    {
        render                 : template,
        startWithMonth         : moment(),
        multiDayEvents         : {
            startDate: 'dateFrom',
            endDate  : 'dateTo',
            singleDay: 'date'
        },
        daysOfTheWeek          : weekdays,
        showAdjacentMonths     : true,
        adjacentDaysChangeMonth: true,
        events                 : events
    }
);
```

**Comment by alexschomb** [comment]
Here is an addition to the solution of @friedemannsommer that considers the current moment.js locale setting. The solution should be universal and could be integrated into CLNDR itself to make things easier.

    var weekdays = moment.weekdays(); // or: weekdaysMin(), weekdaysShort()
    weekdays.concat(weekdays.splice(0, moment.localeData()._week.dow));
    
    $('#my-awesome-calendar').clndr({
        daysOfTheWeek: weekdays
    });

**Comment by asantos00** [comment]
Is it still considered an issue? Or is it supposed to be handled by someone who uses CLNDR?

**Comment by friedemannsommer** [comment]
@alexschomb yeah you're right there should be a universal solution. But i think it would be better if CLNDR doesn't handle this.
