### ISSUE TITLE
Can't pass an object to dateParameter?

### ISSUE THREAD

**Issue by zomars** [kylestetz/CLNDR#152]
I'm trying to use this plugin to get events from a Google Calendar via de the API v3, this is my json, but I can't set the date parameter because it's inside an array, I've tried to put it like this:

dateParameter: 'start.dateTime',

and 

dateParameter: 'start[0]',

with no results, is there a way I can acomplish this? any help is deeply appreciated, this is an extract of the output from the Google API:

 "items": [
  {
   "summary": "Hello World",
   "start": {
       "dateTime": "2015-02-27T09:00:00-07:00"
    },
  },
]

**Comment by kylestetz** [comment]
Yes, `dateParameter: 'start.dateTime'` and `dateParameter: 'start[0]'` are going to fail, since clndr can't arbitrarily reach into your event objects that way. Instead you'll need to take the result of your Google Calendar request and create a new array with formatting that clndr can understand. This isn't a big deal:

```javascript
// assuming we have a `result` object that came from Google Calendar,
// map the object onto a new array that clndr can read more easily.
var myEvents = results.items.map( function(item) {
  item.startDate = item.start.dateTime;
  return item;
});

// now each event object in the array has a `startDate` property that clndr can access.
$('#my-calendar').clndr({
  events: myEvents,
  dateParameter: 'startDate'
});
```

**Comment by zomars** [comment]
Thank you for the response, I came up with a similar approach but this seems better coded. Keep up the good work and thanks again.
