### ISSUE TITLE
Repeat Last Day Of Month

### ISSUE THREAD

**Issue by GuilhermeLessa** [kylestetz/CLNDR#153]
When I put a multy day event that spans two months he has problems with the days of division ( 28 or 29 or 30 or 31 and day 01 of the next month) . I believe it is the problem of repetition of the last day of the month in the early days adjacents . 

Its correct , not to be more 29, 30 , 31 (so next month(adjacent)) 31 , 1, 2 ...

Understand?

**Comment by GuilhermeLessa** [comment]
Example de problems: 
multi-day event 2015-03-27 and 2015-04-03

highlight so happens between 2015-03-28 and 2015-04-02

**Comment by GuilhermeLessa** [comment]
Any way to fix this repetition of the last day?

**Comment by mikegioia** [comment]
@GuilhermeLessa is there any way you could provide an example configuration and possibly even a screenshot of the problem you're describing? The sample config will help me try to replicate it easier, but I'm not entirely sure what is repeating.

**Comment by mizuti** [comment]
Sorry, I don't know the best way to represent this on github (new here). 

I had the same issue, I changed
var i = 1;

to

var i = 2; 

and the months seemed to line up correctly and I did not have any duplicates of the last month styled with "adjacent-month".

Line 324
```javascript
    // ...and if there are any trailing blank boxes, fill those in
    // with the next month first days
    var i = 2;
    while(daysArray.length % 7 !== 0) {
      if(this.options.showAdjacentMonths) {
        var day = moment.utc([currentMonth.year(), currentMonth.month(), numOfDays + i]);
        daysArray.push( this.createDayObject(day, this.eventsNextMonth) );
      } else {
        daysArray.push( this.calendarDay({ classes: this.options.targets.empty + " next-month" }) );
      }
      i++;
    }
```

**Comment by mikegioia** [comment]
@mizuti In the latest version, that line number doesn't match up. Are you using v1.2.15?

**Comment by mizuti** [comment]
Oo I did not check that. I am on v1.2.4
