### ISSUE TITLE
The entire day on the calendar as link URL

### ISSUE THREAD

**Issue by GigaMedios** [kylestetz/CLNDR#158]
I need a simple calendar with only single event / day

Based on this post https://github.com/kylestetz/CLNDR/issues/20  i want my events to go to a scpecified URL when they are clicked.

Unfortunately the code from the post won't work for me, could you provide a working code. thanks

**Comment by kylestetz** [comment]
The idea behind clndr is that you supply your own HTML template that uses the data however you need it to— unfortunately I cannot write it for you. I would be happy to take a look at some markup if you are running into a bug, but the issue you linked to has plenty of information to get you started.

Sorry I couldn't be more helpful! Please open a new issue if you have a more specific question.
