### ISSUE TITLE
Add CLNDR to CDNJS

### ISSUE THREAD

**Issue by webteckie** [kylestetz/CLNDR#161]
Consider adding CLNDR to https://cdnjs.com/

**Comment by mikegioia** [comment]
@webteckie I was browsing through the requirements to CDNJS and it seems pretty time consuming :/ My only hesitation with adding it to this CDN is that CLNDR is already being published to NPM, Bower, and Git.

Perhaps @kylestetz could offer his opinion on this too.

**Comment by webteckie** [comment]
@mikegioia where did you read about the stringent requirements for CDNJS?  Almost every popular library you can think of is there.  It would be very nice to see CLNDR there since I think it deserves to be there.  I have not personally published a library to CDNJS but use many libraries from there and if needs help I may be able to.  I also have a project that only wants to use CDNJS for requiring libraries :-)

BTW, your amazing work on CLNDR thus far is greatly appreciated!!!

**Comment by mikegioia** [comment]
@webteckie Yea perhaps you're right. It looks like CDNJS can auto-update too. I'll try submitting a pull request later today.

**Comment by kkamkou** [comment]
vote up, +1

**Comment by mikegioia** [comment]
I just checked and CLNDR is added to and updating at CDNJS. I think @PeterDaveHello was the one who originally set it up so thank you! This looks to be auto-updating as well, since 1.4.3 is now in there. Closing it out!

**Comment by PeterDaveHello** [comment]
np
