### ISSUE TITLE
Current Date button?

### ISSUE THREAD

**Issue by L0G1C** [kylestetz/CLNDR#164]
I'm trying to figure out how the "next month" and "previous" month buttons work, so that I can add a button to go to "today". If someone has gone back to 2 years ago and wants to get back to present datetime, currently they have to click on "next" arrow  24 times? Is there any built-in way to create a "current date" button?

**Comment by kylestetz** [comment]
Yep, just add the class `clndr-today-button` to any button or link within your clndr template and it will automatically send you back to the current month.

The clndr example page in the repo contains a template with a "today" button, which you can find in [index.html](https://github.com/kylestetz/CLNDR/blob/master/example/index.html#L31).
