### ISSUE TITLE
Link to URL when event is clicked (asp.net)

### ISSUE THREAD

**Issue by itsfranhere** [kylestetz/CLNDR#166]
<p>I want my events to go to a specified URL when they are clicked.
Here is what I have:</p>

$(document).ready(function () {

    $('#calendar').clndr({
        template: $('#calendar-template').html(),
        events: [ 
            { date: '2015-04-09', title: 'CLNDR GitHub Page Finished', url: 'http://www.google.com' 

             },
             { date: '2015-04-19', title: 'CLNDR GitHub Page Finished', url: 'http://github.com/kylestetz/CLNDR'

             },
             { date: '2015-04-25', title: 'CLNDR GitHub Page Finished', url: 'http://github.com/kylestetz/CLNDR',

             }
                ],

        clickEvents: {
            click: function (target) {
                window.location.href="target.events[0].url"; (added this line but it doesn't work properly)
                console.log(target);
            },
            onMonthChange: function (month) {
                console.log('you just went to ' + month.format('MMMM, YYYY'));
            }
        },
        doneRendering: function () {
            console.log('this would be a fine place to attach custom event handlers.');
        }
    }); });

Why it is not working properly? Thank you in advance!

**Comment by robclancy** [comment]
This is what I have...

```js
click: function(target) {
            if (target.events.length) {
              window.location.href = '/panoramas/'+target.date.format('YYYY/MM/DD/');
...
```

**Comment by franzxzxzx** [comment]
# Thanks for your help! I appreciate that :)
I've already sorted it out. I hope this helps you too :)

`clickEvents: {
            click: function (target) {
                console.log(target);
                var output = "";
                for (i = 0; i < target.events.length; i++) {
                    output += " -> " + target.events[i].title + " <br /> ";
                }
                //alert("Events for day: " + target.date.toString() + " \n " + output);
                document.getElementById("tab3").innerHTML = "Events for day: " + target.date.toString() + " <br /> " + output;  `

**Comment by mikegioia** [comment]
Closing this out.
