### ISSUE TITLE
lotsOfEvents help in HTML

### ISSUE THREAD

**Issue by flaviopira** [kylestetz/CLNDR#170]
First I would like to say that the code is fantastic, Congratulations!

I have a question I imagine it to be simple, but I'm not getting.

In javascript everything was understood and the calendar itself is ok, but when I click on date to view events, ss only days and days with start and end can not separate this in html, I tried to use ASP, but it fails.

Could you help me, follows the code?

Thank you.

//javascript
    events: lotsOfEvents,
    multiDayEvents: {
    startDate: 'start',
    endDate: 'end',
    singleDay: 'date',

//HTML
            <div class="events-list">
                {% _.each(eventsThisMonth, function(event) { %}
                  <div class="event">
                    <div class="event-item-data">{%= moment(event.date).format('D MMMM') %} {%= moment(event.start).format('D MMMM') %} e {%= moment(event.end).format('D MMMM') %}</div>
                    <div class="event-item-name">{%= event.title %}</div>
                    <div class="event-item-location">{%= event.location %}</div>
                  </div>
                {% }); %}
            </div>

**Comment by mikegioia** [comment]
@flaviopira is this still an open problem or were you able to resolve it?

If not, could you please clarify what you mean by:
> when I click on date to view events, ss only days and days with start and end can not separate this in html, I tried to use ASP, but it fails.

What particularly doesn't work?
