### ISSUE TITLE
List view only?

### ISSUE THREAD

**Issue by LarkR** [kylestetz/CLNDR#171]
Hi I'm trying to get the calendar to display the list view only like it shows on the right side of the large calendar on main clndr.js site:

http://kylestetz.github.io/CLNDR/

In other words, I don't want the grid calendar to display at all.

It works--until I check it on Safari. When I inspect the element on Safari, the "event-items" are non-existent. But it works perfectly on both Chrome and Firefox. 

Since it works on other browsers other than Safari, I know I included all the necessary files.

What could cause only Safari to do this? What can be done or what am I missing?

       <div class="container">
           <div id="full-clndr" class="clearfix">
           <script type="text/template" id="full-clndr-template">
           <div class="event-listing">
           <% _.each(eventsThisMonth, function(event) { %>
           <div class="event-item">
           <div class="event-item-date"><%=moment(event.date).format('MMMM Do, YYYY') %>
           </div><div class="event-item-location"><%= event.location %></div>
           </div>
           <% }); %>
           </div>
           </script>
           </div>
      </div>

Thanks, I'm pretty new to customizing javascript, so please bear with me!

**Comment by mikegioia** [comment]
@LarkR would you be able to pull the latest from #master and try this again in Safari? I'll run the tests file in Safari when I get home but I just want to verify that it's still an issue.

One test you could run would be to add:
```
<% console.log( eventsThisMonth ) %>
```
from within your template to see if any events in fact are in the register.
