### ISSUE TITLE
Scroll by number of weeks (not by month)

### ISSUE THREAD

**Issue by ShinShinman** [kylestetz/CLNDR#174]
Hi.
Is it possible to scroll calendar by several weeks?
I've found this `moment().add(21, 'days');` but can't get it to work.

Thanks.
Olaf

**Comment by mikegioia** [comment]
@ShinShinman Hi Olaf, you can now do this with the current release of CLNDR. The configuration would look like this:

```
lengthOfTime: {
    days: 21,
    interval: 21
}
```
This would create a 3-week calendar and scroll 3 weeks at a time. If `interval` was 7 then it would scroll 1 week at a time.

**Comment by ShinShinman** [comment]
Great! Thanks a lot.
