### ISSUE TITLE
When using with Browserify, it requires modular assets (jQuery and Moment)

### ISSUE THREAD

**Issue by jsumnersmith** [kylestetz/CLNDR#182]
When trying to run the latest version of CLNDR (1.2.10) using Browserify, I was unable to mix a modularized CLNDR plugin with global jQuery and moment (which are brought in from other parts of my application).

**Comment by mikegioia** [comment]
@jsumnersmith Sorry, I'm unfamiliar with browserify in this regard. Do you happen to have any more info about what isn't working? You're saying CLNDR is requiring jquery/underscore dependencies that you already have global? If that's correct, then why isn't CLDNR using the global $ and _ ?

**Comment by kylestetz** [comment]
@jsumnersmith is saying the opposite— that if he uses browserify, clndr will try to require moment and jquery (because of its requirejs-compatible configuration) and there is no way to prevent that from happening. @jsumnersmith we'll have to check out the browserify docs on this one.

**Comment by mikegioia** [comment]
@jsumnersmith In the interest of cleaning out stale issues, is this still a problem for you? Nothing's been updated on it since last July.

If it is still a problem, I think the next step would be submitting something I can run to reproduce the problem. Otherwise I'll close it out.

**Comment by jsumnersmith** [comment]
Hey @mikegioia I haven't had the issue since then (but I'm not sure if I've tried to reproduce). Feel free to close it up.

**Comment by mikegioia** [comment]
Thanks, anything that comes in related I'll know to open this one back up.
