### ISSUE TITLE
Next & previous month not working correctly with today

### ISSUE THREAD

**Issue by arnodeclercq** [kylestetz/CLNDR#185]
Hi,

The next and previous months doesn't seem to change when using the today button.
First I navigate to another month using the next or previous button, then I use the today button to go back to the current month. When I now use the next or previous month it goes to the next month of the one that was shown before clicking the today button.

Example: 
Current month is June.
I navigate with next to July. 
I use the today button and go back to June. 
Now I click next and clndr goes to August.

Weirdly enough this problem does not occur in the index.html example but it does in test.html (passInATemplate test).
Any idea to why this is happening or how to fix this?

Additional information, this is how I initialise clndr;

>$.ajax({
>    type: "POST",
>			data: {calendar: 'stoptasks'},
>			success: function (data) {
>				$('.calendar').clndr({
>					events: data,
>					constraints: {
>						startDate: '2000-01-01',
>						endDate: '2020-12-31'
>					}
>				});
>			}
>		});

Thanks in advance.

**Comment by mikegioia** [comment]
I'll check this out over the weekend, but thanks for the details. There's probably something weird in the config if it works in index but not test.

**Comment by mikegioia** [comment]
@arnodeclercq This is fixed in the branch issue185. If you have the time and would like to verify it works, please pull and checkout issue185. Otherwise, I'll test this once more at work tomorrow and merge it in to master.

**Comment by arnodeclercq** [comment]
I've tested the changes and the bug seems to be resolved.
Thanks!

**Comment by clemensp** [comment]
Hello,

When is this fix planned to be merged in?
I've run into the same bug, and I'd like to decide whether I want to wait for the next release, or if I want to apply a temp fix.

Thanks!

**Comment by mikegioia** [comment]
Crap I totally forgot to merge it in. I'll do it now, sorry y'all.

**Comment by mikegioia** [comment]
This is now merged into 1.2.15.

**Comment by clemensp** [comment]
Thanks for the quick resolution.

Much appreciated! :+1:
