### ISSUE TITLE
Add destroy() method

### ISSUE THREAD

**Issue by mikegioia** [kylestetz/CLNDR#187]
The class should have a way to destroy a CLNDR instance, optionally to destroy the DOM inside as well. This would allow for re-rendering of the calendar with new options.

**Comment by SNiels** [comment]
I need this too

**Comment by mikegioia** [comment]
@SNiels This is also in the version-1.3 branch. You can reference it as a `.destroy()` method on the CLNDR instance.

**Comment by mikegioia** [comment]
This is resolved in 1.3.0

**Comment by SNiels** [comment]
Works great, thank you.
