### ISSUE TITLE
Re-Rendering causes click events to stop working.

### ISSUE THREAD

**Issue by Maclanahan** [kylestetz/CLNDR#188]
I'm setting up a calendar system that switches out events depending on the the place selected.

I've run into an issue when re-rendering the calendar my click events stops working.

This is the error chrome prints:
//Uncaught TypeError: Cannot read property 'format' of undefined//

It refers to line 707 in the code. 
Before I re-render, my click events still work like a charm.
If I just call mycalendar.render() this issue doesn't come up.
It only happens after calling setEvents(), addEvents(), removeEvents().

**Comment by mikegioia** [comment]
How are you going about re-rendering the calendar?

**Comment by mikegioia** [comment]
@Maclanahan do you have any update on this? I just need to know how you're re-rendering the calendar first. The best thing you could provide would be detailed steps to reproduce this, and hopefully any code/config that you used. That way I could re-create the error the fastest and hopefully patch it.

**Comment by lukefrake** [comment]
I had a similar case with the destroy function and events. My PR #216 might fix this.

**Comment by mikegioia** [comment]
I'm closing this out from inactivity.
