### ISSUE TITLE
clndr 1.2.12 Cannot read property 'format' of undefined error

### ISSUE THREAD

**Issue by tzd** [kylestetz/CLNDR#192]
Hi, with the latest version of clndr I got `error: Cannot read property 'format' of undefined` (line 707) when I click on any calendar day. Please check http://codepen.io/anon/pen/GJxBXg. On 1.2.10 works ok.

**Comment by mikegioia** [comment]
Thanks @tzd, I think this is a scope issue on `this` in that filter() method. I should be able to patch this in a few hours.

**Comment by MikaelX** [comment]
Hi, i have the same issue but only when I add the events through calendar.addEvents([]); I have not tested to add the events by the normal options object on init.

**Comment by mikegioia** [comment]
Ah actually this is a bug on line 1177, the `_clndrDateObject` doesn't exist as it's commented out, I'm going to use the start date on line 708 to fix this.

**Comment by mikegioia** [comment]
@tzd @MikaelX could you try now with 1.2.14? That's the current latest. I tested it on the same codepen and it looks to be working.

**Comment by tzd** [comment]
Hi, it works for me, thank you for the fix.

**Comment by MikaelX** [comment]
Thanks, that works now :)
