### ISSUE TITLE
Having two different kinds of event objects

### ISSUE THREAD

**Issue by ipsgandhi** [kylestetz/CLNDR#194]
var events = [
    { eventdate: '2015-07-11', title: 'Persian Kitten Auction', location: 'Center for Beautiful Cats' },
    { appointmentdate: '2015-17-11', reason: 'Not Well', Doctor: 'Mr. Makemehealthy' },
  ];

Is it possible to have this kind of events in the calendar ? Maybe a type can be added to distinguish between the two.

**Comment by mikegioia** [comment]
@ipsgandhi You can add any info to the events array and you'll have access to those properties in your template. In your case, you would want to do:

```
var events = [
  {
    data: '2015-07-11',
    title: 'Persian Kitten Auction',
    location: 'Center for Beautiful Cats',
    type: 'event'
  }, {
    date: '2015-17-11',
    reason: 'Not Well',
    doctor: 'Mr. Makemehealthy',
    type: 'appointment'
}];
```
Then in your template you could use the `type` field to render data differently.

**Comment by mikegioia** [comment]
@ipsgandhi I'm going to close this out unless you had any other questions or updates as it's been over 30 days.
