### ISSUE TITLE
Firefox - Duplicated date (2015-10-17)

### ISSUE THREAD

**Issue by alepaez** [kylestetz/CLNDR#196]
2015 - 10 - 17 is appearing twice on Firefox
![date array](http://s7.postimg.org/3u1m596nv/Screen_Shot_2015_07_27_at_2_03_18_PM.png)
![view](http://s7.postimg.org/n9cdyczy3/Screen_Shot_2015_07_27_at_2_00_22_PM.png)

**Comment by mikegioia** [comment]
Thanks @alepaez for the details. I'm gonna investigate this and #153 as they both have to do with what feels like a looping or counter issue.

**Comment by kylestetz** [comment]
@alepaez what time zone are you in? We've had some issues with a specific timezone that seem to be related to a general JS `Date` bug. I'm looking for the issue where we discussed this...

**Comment by kylestetz** [comment]
Found it: #131. Is this only happening in Firefox, or can you replicate it across all browsers?

**Comment by alepaez** [comment]
Thank you guys!
@kylestetz I'm in GMT -3. It's only happening in Firefox (Tested in Chrome, Safari and Firefox)

**Comment by kylestetz** [comment]
I can't reproduce this. Can you tell us about your development environment? OS, browser version, clndr version, etc.

**Comment by alepaez** [comment]
I'm running clndr.min.js v1.2.0 on production.

Customer who reported the bug environment: 
  Windows 7, Firefox 39.0 

My development environment:
  OSx Yosemite, Firefox 38.0.5

Already tried to update to clndr.min.js v1.2.15, but the bug persisted.

**Comment by kylestetz** [comment]
Interesting, we're in the same environment but I can't see this one.

As an aside, definitely use v1.2.15! It is fully backwards-compatible down to 1.2.0 and some nice things have been introduced since.

**Comment by alepaez** [comment]
jQuery version could have influence on this bug?

**Comment by kylestetz** [comment]
Sure it's possible, and actually `moment` would be the more likely candidate to mess things up. I am testing the [example/index.html](https://github.com/kylestetz/CLNDR/blob/master/example/index.html) page in the clndr repo, which loads jquery `v1.10.2`, moment `v2.8.3`, and underscore `v1.5.2`.

**Comment by alepaez** [comment]
Ok, those are the versions I have here.
jquery: 1.8.2
moment: 2.9.0
underscore: 1.4.2

**Comment by davovscapcom** [comment]
It looks like this issue is related to when daylight savings time ticks over. In my region, October 3 is being duplicated, which marks the beginning of daylight savings time.

**Comment by mikegioia** [comment]
I've re-tested this in FF with the latest libraries and can't recreate it at all. I've tried changing to many different timezones and the calendars render correctly in FF and Chrome on linux. I'm going to close this as it's gone stale (11 months) but @alepaez please feel free to re-open this if you can recreate it with the current, up-to-date libraries and can provide the full environment info.

I suspect that if it's related to #131 in any way then it's a UTC / DST issue for browsers in certain timezones but I just can't duplicate the error :frowning:
