### ISSUE TITLE
Disable Previous Button if month is a past month

### ISSUE THREAD

**Issue by darwinluague9001** [kylestetz/CLNDR#198]
Is there any way that I can disable the previous button when the month is already past. Like for example the current month is August and I cannot go back to July.

**Comment by kylestetz** [comment]
Sure! There is a feature in clndr called [Constraints](https://github.com/kylestetz/CLNDR#constraints--datepickers). It allows you to prevent the user from moving beyond a date, either in the past or in the future (or both!). In your case, you can set it up like this:

```javascript
$('#my-calendar').clndr({
  // other configuration...
  constraints: {
    startDate: moment().startOf('month')
  }
});
```

This tells clndr to prevent the user from moving to a month prior to this month. This will add a `disabled` class to the previous month button— it's up to you to style it in CSS so the user doesn't think it's broken.

**Comment by darwinluague9001** [comment]
Thanks @kylestetz
