### ISSUE TITLE
''Title of event''

### ISSUE THREAD

**Issue by krlnr** [kylestetz/CLNDR#199]
Hello,
I have a problem with my ''title'' of my event, they doesn't appear in my web page...

![capture d ecran 2015-08-10 a 08 45 19](https://cloud.githubusercontent.com/assets/10655618/9160617/26101fca-3f3c-11e5-95bf-0dc13fabe02f.png)

**Comment by kylestetz** [comment]
Hi Léo! You are using the default clndr template which doesn't show event titles. If you want your calendar to have event titles in it, you'll have to write your own template. You can read more about writing templates [in the clndr documentation](https://github.com/kylestetz/CLNDR#introduction-you-write-the-markup).

I'm going to close this issue for now, but feel free to open a more specific one if you get stuck somewhere.
