### ISSUE TITLE
Wrong events triggered

### ISSUE THREAD

**Issue by kapke** [kylestetz/CLNDR#200]
When clicking "next month" button, there is "previousMonth" callback called. Need to check if there are more mistakes like this one.

If needed, I think I'm able to propose solution for that

**Comment by mikegioia** [comment]
@kapke I don't see where this is happening. Do you have a line number or any more information?

**Comment by kapke** [comment]
Sure: look at gist I linked. It doesn't matter which control you click (next or previous month), always is triggered event notifying that you clicked _previous month_ control. Months are changing properly.
https://gist.github.com/kapke/0677bd34a8130c401b10

**Comment by mikegioia** [comment]
@kapke I think I found the bug. If you wouldn't mind, could you pull branch "issue200" and check your script against that? I'm pretty sure it can go into master but I'd like to check first.

**Comment by kapke** [comment]
It looks that unminified version works properly now.

**Comment by mikegioia** [comment]
Thanks, yea I didn't minify it in this branch. I'm going to merge this into master and rebuild it all.

**Comment by mikegioia** [comment]
This is resolved in v1.2.16
