### ISSUE TITLE
Link between days and events

### ISSUE THREAD

**Issue by MirkoWeb** [kylestetz/CLNDR#203]
Can I create a "link" between days and events in the template or JS events of CLNDR?
For example, I would make that mousing over a particular day it highlights the event attached to it.

Thank you

**Comment by mikegioia** [comment]
In your template, you could attach class or data- attributes pertaining to your events. And in your events list you could attach the similar properties to each event. I think you could then tie event behaviors to items with those class name/data attributes to interact with each other.
