### ISSUE TITLE
Disable specific dates?

### ISSUE THREAD

**Issue by eduavila** [kylestetz/CLNDR#209]
how do I disable specific date? and if as a day of the week? eg disable every Sunday.

**Comment by mikegioia** [comment]
You would need to do this in your template/rendering. A good way to do it would be to check which day of the week it is in your template, and skip that day in your loop so as not to render the day. Or add a class to it and hide it via CSS.

**Comment by eduavila** [comment]
You have some sample using template / rendering ?

**Comment by mikegioia** [comment]
Something like this:

```
<% _.each( days, function ( day ) { %>
    <% if ( i % 7 === 0 ) { %>
    <div class="week">
    <% } %>
    <% if ( extras.options.show_weekends || ! ( i % 7 === 0 || i % 7 === 6 ) ) { %>
        // Show the day here
    <% } %>
    <% if ( i % 7 == 6 ) { %>
    </div><!-- /week -->
    <% } %>
    <% i++ %>
<% }); %>
```
You're iterating over the days array, but this is just one example of, say, 'hiding weekends'. I use this in my app, and the `extras.options.show_weekends` is passed in as configuration on the CLNDR instantiation:

```
...
extras: {
    options: {
        show_weekends: false
        ...
    },
    ...
},
...
```

**Comment by eduavila** [comment]
perfect. thank you.
