### ISSUE TITLE
How to limit events per day?

### ISSUE THREAD

**Issue by kienerj** [kylestetz/CLNDR#210]
I would like to limit events per day and color days green if event is available and red if not.

Especially the coloring seems to pose some problems. I would do this in the "doneRendering" function, correct? I can get all days with an event through jquery selectors. But the problem now is, how can I easily get the 'target" object of each day?

That does not seem possible, I would have to extract the date out of the calendar-day class and then look up events in the events array manually.

Or I could get all events from current month (but they should include end/start of last month too), find all dates with more than 6 events and then find the according days and change color to red. This would be even more troublesome as there would be no easy way to select the DOM element by date?

Or am I missing something?

A function like clndr.get(date) that returns the target object would be extremely helpful. Also if the day would have custom data attribute like "data-eventids" = "2,3,5" with event indexes from events array.

**Comment by kylestetz** [comment]
Hey @kienerj! This is definitely something clndr can help you achieve. The key is to write a template that adds classes to the events based on the circumstances you just outlined. Have a look at #6, which shows you how to take data from your events and inject it into a template.

If you put all of the logic for coloring events in your template, you shouldn't have to write any additional javascript! I am closing this particular issue, but feel free to open a new, more specific issue if you run into any trouble.
