### ISSUE TITLE
Disable trackSelectedDate for inactive days

### ISSUE THREAD

**Issue by trottera** [kylestetz/CLNDR#213]
i'm trying to use CLNDR as a date picker. 

I would like to disable the functionality, that you can select a inactive date. I guess i could check for the inactive class on the click event, and revert the selection. But i'd rather disallow the selection of a inactive day in the first place.

Is there any way to do this?

**Comment by kylestetz** [comment]
There is currently no way to do this!

How about an `ignoreInactiveDaysInSelection` option, which you can set to  `true` when you instantiate clndr, so that it will ignore days with the `inactive` class on it? Would that work for you?

**Comment by trottera** [comment]
yes, that would be perfect.

**Comment by kylestetz** [comment]
Just published `v1.3.3` which has this option! I think you'll figure it out, but if you want a working example I've added one [to the test suite here](https://github.com/kylestetz/CLNDR/blob/master/example/test.js#L388).

Cheers :beers:
