### ISSUE TITLE
show/hide calendar

### ISSUE THREAD

**Issue by ambicoder** [kylestetz/CLNDR#214]
How I could achieve that the calendar appears on clicking a button...I want it to be hidden originally.
Furthermore...when it gets to be shown I want it to be done using css transitions.

But first(let us forget the transitions for now) I tried to achieve what is described above with this https://jsfiddle.net/fiddlehunt/m4mdyjnr/ 

I set the div element(where the calendar in initialized) to display:none and try to remove that with css jquery property with a click handler

It does not work as you see...what do you propose?

**Comment by mikegioia** [comment]
@ambicoder you have two errors in that fiddle:

1. The id should be `"show"` you have `"show    "`. Change this to be:

    ```
    <div id="sidebar"><input id="show" type="button"  value="show calendar!"></div> 
    ```
2. it's `display: block` not `display:visible`. Change the JS to be:

    ```
    $("#calendar").css( "display", "block" ); 
    ```

**Comment by ambicoder** [comment]
I have managed to do the show/hide part....I am not closing the issue yet cause I want to do the transition part.Thanks for the help so far.
https://jsfiddle.net/fiddlehunt/m4mdyjnr/

**Comment by ambicoder** [comment]
I found a solution after all in transitioning the element....thanks anyway.
