### ISSUE TITLE
Destroy function breaks previous next events

### ISSUE THREAD

**Issue by lukefrake** [kylestetz/CLNDR#215]
I have to run the destroy function on the clndr and rebuild. On the face of this doing it is absolutely fine.

On second look, it means that the previous and next buttons stop working. I've had a dig through the code and context.element is null still from the destroy. It seems like the events are still in place from the initial destroy.

**Comment by kylestetz** [comment]
Nice, sounds like you're on top of this one— can you give me the steps to reproduce the problem or post the code you're using that exhibits the bug?

**Comment by lukefrake** [comment]
Below code should work for you.

```
clndr = $( '#clndr' ).clndr( { ... } )
clndr.destroy()
clndr = $( '#clndr' ).clndr( { ... } ) // This one won't have events for prev or next
```

Does that help enough? :dancer:

**Comment by danielepennati** [comment]
I have the same issue
