### ISSUE TITLE
selectedDate doesn't work

### ISSUE THREAD

**Issue by Gespinha** [kylestetz/CLNDR#217]
Hi there,

I have the following setup for my clndr instance:

         window.calendar = $('#calendar').clndr({
            template: $('#calendar-template').html(),
            adjacentDaysChangeMonth: true,
            trackSelectedDate: true,
            selectedDate: '2015-10-11'
        });

But, although I have set the selectedDate to a certain date and the calendar opens in the select month, the selected date doesn't have the .selected class.

Why is this?

I just want to have a default selected date.

**Comment by kylestetz** [comment]
I tested this and it works for me. What version of clndr are you using? The selected date feature was added in `v1.2.11` and I just pushed `v1.3.4` this morning which I would encourage you to use.

**Comment by Gespinha** [comment]
Hi @kylestetz I've just updated to v1.3.4 and I have this as an option:

selectedDate: '2015-10-13'

but it doesn't seem to work.

**Comment by kylestetz** [comment]
Can you create a JSBin that replicates the issue so that I can take a look?

**Comment by Gespinha** [comment]
Oh, nevermind I've just discover it is actually working, but the calendar isnt focused on the selected month when I start the page. How can I make it focus on the month of the selected day?

**Comment by kylestetz** [comment]
There is a `startWithMonth` option that takes a date string or a moment object. Have a look at the [Usage docs](https://github.com/kylestetz/CLNDR#usage) for more options you can use on startup!

**Comment by Gespinha** [comment]
@kylestetz Thanks, that works :)

Just another small detail, how do I set the calendar date dynamically through the instance?

I've tried something like this, but it didn't work:

`window.calendar.options.selectedDate = "2013-05-29"``
