### ISSUE TITLE
Can't set a date through external link

### ISSUE THREAD

**Issue by Gespinha** [kylestetz/CLNDR#218]
Hi there,

How do I set the calendar date dynamically through the instance?
I've tried something like this, but it didn't work:

`window.calendar.options.selectedDate = "2013-05-29"`

What am I doing wrong?

**Comment by mikegioia** [comment]
@Gespinha Do you have sample code? I can't tell without knowing the scope of your `calendar` variable.

If you look at the docs, selectedDate is a configuration option you can set during initialization.

**Comment by Gespinha** [comment]
@mikegioia I just found the solution for my problem, forgot to close the issue. Thanks anyway! :)
