### ISSUE TITLE
Weekly 7-day Calendar; integration myBB etc

### ISSUE THREAD

**Issue by ollie007** [kylestetz/CLNDR#221]
How do i display the current weekly 7 day calendar or any period? as a slider on top?

rather than have the usual, 30 day box?

**Comment by daseinhorn** [comment]
#13

**Comment by kylestetz** [comment]
No need to refer to #13, a feature was added in the spring that allows you to do this. See the `lengthOfTime` option in the [Usage section of the docs](https://github.com/kylestetz/CLNDR#usage).

```javascript
$('#my-calendar').clndr({
  lengthOfTime: {
    days: 7,
    interval: 7
  }
});
```

Now in your template you will have a `days` array of length `7` and all clndr controls (next, previous, today, next year, previous year, etc) will work as usual.
