### ISSUE TITLE
Returning single events

### ISSUE THREAD

**Issue by wcd-calum** [kylestetz/CLNDR#224]
On creating a template to display the event clicked on; the documentation only seems to go as far as the function 'eventsThisMonth' which will return a list of events for the that month. Is there an 'eventsThisDay' type function that could be used for returning the result of just the date clicked on?

**Comment by kylestetz** [comment]
Check out the [Usage](https://github.com/kylestetz/CLNDR#usage) section of the docs, which outlines all of the options you can pass clndr. The `clickEvents.click` event handler is the one you're looking for; it will pass a `target` object which contains the date you clicked on, the original element, and an array of all events that are happening on that day.

```javascript
$('#my-calendar').clndr({
  clickEvents: {
    click: function(target) {
      console.log('The day you clicked on has the following events:');
      console.log(target.events);
    }
  }
});
```

**Comment by ikhan009** [comment]
i want to show only day events, not whole month events.  how i show?
here i pass "eventsThisMonth", there is other parameter for day click event?

<div class="events-list">
   <% _.each(eventsThisMonth, function(event) {%>
        <div class="event" style= "color:white;">
            <a  href="<%= event.url %>" onclick="showDialog('<%= moment(event.date).format('YYYY-MM-DD')%>')" ><%= moment(event.date).format('MMM Do') %>: <%= event.title %>
           </a>
         </div>
<% }); %>
</div>

**Comment by ikhan009** [comment]
other Question, 
i want to show model on other days click, where no events.
how i show model there?
