### ISSUE TITLE
Small enhancements for Version 1.4

### ISSUE THREAD

**Issue by mikegioia** [kylestetz/CLNDR#225]
The main purpose of [1.4](https://github.com/kylestetz/CLNDR/milestones/CLNDR%201.4) is to do the style cleanup and to get the 1.X series ready for maintenance mode. There are a few things I've noticed in the library that could either be cleaned up now, or they could wait for the re-write in version 2.

##### Consolidate forward/backward events

There are 8 methods to handle moving the calendar forward and backward. Four are simply wrappers/aliases, but the other four are used to go forward/back. These are `forwardAction`, `forwardActionWithContext`, `backAction`, `backActionWithContext`. I think we can combine these by having an optional context argument, defaulting to `this` when called from the userland.

A more thorough eventing update could happen in 2.0 but this could at least remove the duplicated code for now.

##### (Maybe) Remove the default 'month' rendering and enforce use of `lengthOfTime`

Right now are three rendering modes: days, months, and the default "current month". This current month is the legacy method. I think we can remove it by defaulting to a lenghtOfTime of 1 month with a period of 1. The API would need to return the same data in the 1.X branch (which is unfortunate) but it would remove this unnecessary third condition from the library.

This may be better served to wait for the 2.0 release, which I have a rough outline for that I'll present in another ticket.

**Comment by mikegioia** [comment]
I think I have a way to reduce a lot of code in the event functions by consolidating the parts that trigger events.

Also, it appears that events like `onMonthChange` don't trigger when an interval was specified on the config, even if the interval was a 1-month. I think this is probably correct because a) it's simpler and b) it's tough to know if you want this to trigger on say a 3-month calendar.

**Comment by kylestetz** [comment]
I'm way into these changes— consolidating feels good and forcing everything to use intervals is definitely a step in the right direction. The `onMonthChange` and `onYearChange` events firing sounds good to me, I would consider the current behavior buggy based on what you described.

I'm a little concerned about the backwards-compatibility break with template data, just because I want it to be clear to users that the data being returned is dependent on their version. It's not necessarily realistic to expect that everyone will go out and upgrade— some folks will need to maintain sites with older versions.

So: I'm curious to hear your thoughts on v2, if you think it's worth rewriting the plugin. Want to post your thoughts on that?

**Comment by mikegioia** [comment]
> The onMonthChange and onYearChange events firing sounds good to me, I would consider the current behavior buggy based on what you described.

Yea I agree. This would make the events the most consistent imo. It can be added in 1.4.1.

> I'm a little concerned about the backwards-compatibility break with template data, just because I want it to be clear to users that the data being returned is dependent on their version.

I think any bc breaking would happen in 2.0 but you're right. This only really has to do with `month`, `eventsNextMonth`, `eventsThisMonth`, `eventsLastMonth`. There's just some confusion during `render` about what is passed to the view based on the config. We can't kill these vars in any 1.X update but I think any changes here would be good to make in the v2.

> So: I'm curious to hear your thoughts on v2, if you think it's worth rewriting the plugin. Want to post your thoughts on that?

I have an small outline that I can post to get the convo started. I was thinking about it mostly from:

1. Is there a way to break this out into components so that updating is easier?
2. Can the code be reduced/simplified any further?

If (2) is no then it's probably not worth it. But I think there are some gains to be had around converting _everything_ to render via lengthOfTime, with the default being a 1-month calendar. This would allow us to cleanup the data passed to the template once and for all.

**Comment by kylestetz** [comment]
> I think any bc breaking would happen in 2.0

:+1:

> I have an small outline that I can post to get the convo started. I was thinking about it mostly from:
1. Is there a way to break this out into components so that updating is easier?
2. Can the code be reduced/simplified any further?

Just so we're not retreading here, have you read the original proposal we wrote for v2 back in February in #155?

**Comment by mikegioia** [comment]
Yea I think #155 is right on the money. I was thinking of breaking the calendar, config parsing, and rendering portions out but what you've described is better.

Have you started planning anything w/r/t gregorian.js yet? I could get to helping with this pretty soon.
