### ISSUE TITLE
Duplicated Date for Last Day of Month

### ISSUE THREAD

**Issue by c-ni** [kylestetz/CLNDR#227]
Tested in Firefox, Chrome and Edge

The last day of the month is duplicated. I just downloaded this calendar to try out yesterday but I'm pretty sure this problem wasn't there yesterday...
![clndr1](https://cloud.githubusercontent.com/assets/15806389/11448605/7faf2240-9529-11e5-87cb-36ac771f3478.JPG)

jsfiddle: http://jsfiddle.net/duck/aEwNt/

Edited to add: Yes, the problem wasn't there yesterday. I'm guessing someone is updating the code base right now :+1:

**Comment by mikegioia** [comment]
I wonder if this is related to #196. Either way the last day of the month is duplicated for every month here. I'll check this out.

**Comment by mikegioia** [comment]
@c-ni I can't recreate this in the test file. Can you pull down and run `tests/test.html` to verify that it's happening? I'd like to verify if it's moment or clndr.

**Comment by mikegioia** [comment]
@c-ni Your fiddle is using CLNDR version 1.2.4, loaded from the test page. Can you please try running this with the latest version of CLNDR to confirm the error?

**Comment by c-ni** [comment]
Hi Mike,
I'm not at home right now, but will try it when I get home. I'm currently on my iPhone and noticed the same issue on your demo site.

**Comment by mikegioia** [comment]
@c-ni Hm, I think the problem is with that demo site, but I'll have to test it out fully later. The demo site hasn't been updated in a while and I think it uses a static copy of v1.2.4.

**Comment by c-ni** [comment]
@mikegioia That was the issue -- it explained why it worked in my app (was using the latest version), and not on the demo site nor jsfiddle (which was an old one I found on stackoverflow). I updated to the latest version and it works great. Thanks for the amazingly fast responses!

**Comment by mikegioia** [comment]
Sure thing @c-ni Thanks for following up on that.
