### ISSUE TITLE
addEvents without rerender?

### ISSUE THREAD

**Issue by whatnickcodes** [kylestetz/CLNDR#229]
Anyway? Sorry if I'm not seeing it.

**Comment by kylestetz** [comment]
Can't do that at the moment! It's a perfectly reasonable use case though. We can add an optional second `silent` argument to the `addEvents` function that will skip the rendering step.

I can't do this right at the moment but if you want to submit a pull request that would be awesome! Should be a real simple fix, lines [1483](https://github.com/kylestetz/CLNDR/blob/master/src/clndr.js#L1483) and [1495](https://github.com/kylestetz/CLNDR/blob/master/src/clndr.js#L1495) will be of interest. If you do a PR you should add the option to `setEvents` and `removeEvents` as well :grin:

**Comment by ncerminara** [comment]
Ah! No worries and makes sense. Was just trying to animate new events being added to my calendar without the existing ones "blinking" / repeating the CSS animation . Good to know it's an easy fix.

After I wrap everything else up I'll revisit and send a pull

**Comment by mikegioia** [comment]
@whatnickcodes This was now added in 1.4.2.
