### ISSUE TITLE
Period change event not fired

### ISSUE THREAD

**Issue by tonisostrat** [kylestetz/CLNDR#230]
CLNDR.js version 1.3.4
Underscore.js version 1.8.3

I have a div on the page
```html
<div id="test-cal"></div>
```
with the following CLNDR initialization script
```javascript
$('#test-cal').clndr({
    lengthOfTime: {
        days: 7,
        interval: 7
    },
    clickEvents: {
        click: function(target) {
            console.log(target);
        },
        onPeriodChange: function(start, end) {
            console.log("periodChange");
        }
    }
});
```
The calendar is rendered perfectly according to the default template but when I change the period (week in my case), the event is never fired. Neither do **nextPeriod** or **previousPeriod** handlers work.

[Example JSfiddle](https://jsfiddle.net/o0prry4e/).

**Comment by mikegioia** [comment]
@tonisostrat Could you pull down and try this against version 1.4?

**Comment by tonisostrat** [comment]
[Updated JSfiddle]. If you open up **clndr.min.js** from *External Resources* you can see it's at v.1.4.0. The problem persists.

**Comment by mikegioia** [comment]
Sorry, @tonisostrat, the docs are wrong in this case. That's my fault, I actually think they've been typo'd for a while. Anyway, you can use these events: onIntervalChange, previousInterval, and nextInterval.

I should probably alias "period" and "interval" in this case.

**Comment by tonisostrat** [comment]
Thank you, it's been fixed. The events fire with *Interval* :)

**Comment by kylestetz** [comment]
Sorry about that! Just updated the docs. Thanks for catching this @tonisostrat!
