### ISSUE TITLE
Emulate clickEvent: click

### ISSUE THREAD

**Issue by dejan-milicevic** [kylestetz/CLNDR#233]
Hello,

Can I emulate clickEvent: click() from outside of clndr?

**Comment by mikegioia** [comment]
@dejan-milicevic What do you mean emulate a click event? Emulate clicking a day? If so, can do that outside of this plugin with something like:

```
$( '#my-calendar' ).find( '.your-day-classname' ).trigger( 'click' )
```

In your template you can set up any classnames on the days that you want. They also have some added by default. Check the README and the tests file for more info.

**Comment by dejan-milicevic** [comment]
Yes, of course.. In that case I assume I will not be able to use target object?

**Comment by tonisostrat** [comment]
When you trigger a ClickEvent the event handler that you specified in the **clndr({})** initialization code should be fired. There's really no difference between a programmatic or a mouse click on any of the calendar days.

**Comment by dejan-milicevic** [comment]
Understood! Thank you very much for fast answer.

**Comment by atilkan** [comment]
How can i get if the event is triggered or clicked? 
I can't send parameters like usual jquery way. 
ForEx:
`$('#btn').trigger('click', true)`
