### ISSUE TITLE
Successfully tested with Mustache.js

### ISSUE THREAD

**Issue by mcmathews** [kylestetz/CLNDR#235]
[Mustache](https://github.com/janl/mustache.js) is a Javascript templating system and I was able to successfully implement a CLNDR with it. I'm just letting you know so you can add it to the list of supported rendering systems.

The render function can be written as follows:
```javascript
$('#calendar-container').clndr({
    render: function (data) {
        return Mustache.render($('#calendar-tmpl').html(), data);
    },
});
```

The corresponding markup for a normal calendar could look like this:
```html
<script type="x-tmpl-mustache" id="calendar-tmpl">
    <div class="controls">
        <span class="clndr-previous-button">prev</span>
        <span class="month">{{month}}</span>
        <span class="year">{{year}}</span>
        <span class="clndr-next-button">next</span>
    </div>
    <div class="days-container">
        <div class="days">
            <div class="headers">
                {{#daysOfTheWeek}}
                    <div class="day-header">{{.}}</div>
                {{/daysOfTheWeek}}
            </div>
            {{#days}}
                <div class="{{classes}}" id="{{id}}">{{day}}</div>
            {{/days}}
        </div>
    </div>
</script>
```

**Comment by mikegioia** [comment]
Thanks @mcmathews, there's another issue #236 about CLNDR working in Knockout too. I think these both could go into the README file. I'll try to do it this week, but I'd happily accept the PR :stuck_out_tongue:

**Comment by mikegioia** [comment]
This is added in the Readme
