### ISSUE TITLE
Knockout template rendering

### ISSUE THREAD

**Issue by karl-sjogren** [kylestetz/CLNDR#236]
I'm using CLNDR in a knockout project and ported the standard template to knockout to see if it was feasible. No need for underscore (or any other templating language) if you already use knockout. The code is available here https://github.com/karl-sjogren/clndr-knockout

**Comment by mikegioia** [comment]
@karl-sjogren I just updated the Readme with a link to your project: https://github.com/kylestetz/CLNDR#template-rendering-engine
