### ISSUE TITLE
Formatting for Event between Start and End Date is thrown off by UTC

### ISSUE THREAD

**Issue by anthonyhorne** [kylestetz/CLNDR#237]
In multi format date, using the array of valid event dates, the adding of the "event" class is thrown off by the UTC date difference and sometimes excludes the last day of the range, i.e. 5-8 Jan will only show the "event" class for 5-7.  The actual object being returned by the onclick does still confirm that the date is part of the valid events.  I suspect it is because my local is ZA and my timezone is GB.

(day.isSame(end, 'day') ) RETURNS false, even though it is not really (is actually)

line 368 of clndr.js  (search for "woohoo semantics!"). :)

Below what is retuned on my side and effectively fails.

?day
{...}
    __proto__: {...}
    _d: Wed Jan 06 2016 00:00:00 GMT+0000 
    _i: [2016,0,6]
    _isAMomentObject: true
    _isUTC: true
    _locale: {...}
    _offset: 0
    _pf: {...}
?end
{...}
    __proto__: {...}
    _d: Wed Jan 06 2016 00:00:00 GMT+0200 (South Africa Standard Time)
    _f: "YYYY-MM-DD"
    _i: "2016-01-06"
    _isAMomentObject: true
    _isUTC: false
    _isValid: true
    _locale: {...}
    _pf: {...}

WORKAROUND:

If you know or are comfortable with the GMT difference, then you can specify a appropriate time in the Events Array - as below:

multidayMixedArray = [
          { title: 'Multi1', endDate: '2016-01-07 10:00:00', startDate: '2016-01-06 10:00:00',

etc.

Not ideal, but it worked for me.

See: http://stackoverflow.com/a/11805627/1662973 - just for clarification on date diff logic / problem.

**Comment by mikegioia** [comment]
@anthonyhorne Are you able to send a sample array of event data, and a sample config for me to plug this into the browser and replicate? I'm having trouble understanding the issue unfortunately, and I fear it might be due to having two competing timezones in your application.

I'll leave this open for a few weeks to allow you to send over any replication info, but I'll need that (preferably a JSBin) before I can step through any debugging.

**Comment by anthonyhorne** [comment]
@mikegioia Attached is the full example I used - working.  Does NOT work in edge, but works in Firefox (latest) - uses cookies for the array list Meeting / calendar data.  If you choose Jan 2016 (when I did the dev), and choose a option from the combobox on the bottom, it will populate the calendar with events that you can click on which shows some items on the right of the calendar.   As I say, it worked, but required me to include the time which allowed me to fool the time difference.  I still think the comparisons should be consistently UTC or not.  Ran out of time and am not using that dev anymore - hopefully someone else will benefit from the change, or it won't affect them in the first place :)

[FullExample.zip](https://github.com/kylestetz/CLNDR/files/344688/FullExample.zip)

**Comment by mikegioia** [comment]
Thanks @anthonyhorne. Just FYI you're using an old version of CLNDR (1.2.4) that was giving me errors with multi-dates as well in both FF and Chrome. When I upgraded to 1.4.4 (latest) those errors went away.

I opened your example with CLNDR 1.4.4 in IE Edge it worked :D Could you try it with that version?

**Comment by mikegioia** [comment]
I'm going to close this out as its stale, but feel free to re-open the issue. I think it had to do with the old version though.
