### ISSUE TITLE
Zero Pad in calendar days? 

### ISSUE THREAD

**Issue by kray67** [kylestetz/CLNDR#238]
Hi,

Is there a way to make the calendar days 1-9 show as double digit with left zero padding (01-09)?

Thanks in advance!

**Comment by mikegioia** [comment]
@kray67 You're free to design your calendar template any way you want. I think this would be handled in the template and not CLNDR.

**Comment by kray67** [comment]
@mikegioia Thanks for the reply. I eventually got it to work. Was just wondering if there was some way to do this natively with CLNDR or moment.js. Cheers!
