### ISSUE TITLE
Event times available?

### ISSUE THREAD

**Issue by chadmazilly** [kylestetz/CLNDR#250]
Looks like a fantastic plugin that I want to incorporate into an upcoming project. I will need to have specific times for events within each day, however. Ideally, I'd like to have events id'd by `YYYY-MM-DD-HH-MM-SS` for example, and allow overlapping or multiple events scheduled at the exact same time. It appears that this package does not support event times to this level. Am I correct in thinking this? Thanks again for the great looking JS package.

**Comment by mikegioia** [comment]
Yes @chadmazilly, but I'd be open to accepting a PR with support for times. Right now I think the days array only wants an event in `YYYY-MM-DD` format, but there's nothing preventing us from adding times to this. You could extend this by having the days array include a `time` field if there happened to be a time passed in.

I'm closing this for now, but please feel free to submit that if you ever implement it.

**Comment by kylestetz** [comment]
I'm not sure why clndr can't support your use case @chadmazilly. What specifically are you looking for clndr to provide? Do you want the events to be sorted by time?

**Comment by mikegioia** [comment]
Closing this as it's gone stale
