### ISSUE TITLE
Not compatible to Meteor 1.3+

### ISSUE THREAD

**Issue by alexschomb** [kylestetz/CLNDR#257]
It took me a while to figure out, but it appears that CLNDR is unfortunately not compatible to the newest Meteor release. You can get it to working using a workaround (placing it in ``client/compatibility``), but that shouldn't be the way to go. I understand that Meteor compatibility wasn't on your todo list, but it would be great if you had a look. Here are some more details and discussion: https://forums.meteor.com/t/why-your-jquery-plugins-may-be-failing-in-1-3-1/20739

**Comment by mikegioia** [comment]
@alexschomb I think the only way this would get implemented is through a PR. I've never used Meteor before unfortunately, but if you're well-versed in it please submit one :)
