### ISSUE TITLE
force onMonthChange with setMonth

### ISSUE THREAD

**Issue by nicomollet** [kylestetz/CLNDR#259]
Hello

I am adding events with ajax, with the _onMonthChange_ event, like sugested in the issue #120.

_onMonthChange_ is fired after changing month, OK. But it is not fired on the initialization of the calendar, and even after executing

``` javascript
myCalendar.setMonth("February", { withCallbacks: true });
```

The problem I think is, _onChangeMonth_ is not fired if the month in _setMonth_ is the same as the current month.
Is there a way to force _onChangeMonth_ with _setMonth_, or is there a better method to add events with ajax? Thank you.

Kind regards

**Comment by kylestetz** [comment]
@nicomollet you are correct and this is by design— `onMonthChange` only gets called when the month changes. I would suggest taking whatever logic you have inside of `onMonthChange`, putting in its own function, and calling that function when you instantiate your `clndr` instance.

In other words...

```javascript
function getEventsForMonth(month) {
  // take the `month` object and use it to request the correct month
  $.ajax({
    // request something like `/events/2016/04`
    url: '/events/' + month.format('YYYY/MM'),
    success: function(events) {
      clndr.setEvents(events);
    }
  });
}

var clndr = $('#my-calendar').clndr({
  onMonthChange: getEventsForMonth
});

// initial call to `getEventsForMonth` with the current month
getEventsForMonth(moment());
```

**Comment by nicomollet** [comment]
Thanks for your reply, I will do it your way.
