### ISSUE TITLE
day is not defined

### ISSUE THREAD

**Issue by tobz-nz** [kylestetz/CLNDR#270]
#### Context
Hi, I'm getting the error: `ReferenceError: day is not defined`.
My code:

```
$cal.clndr({
    events: [{"date":"2016-07-03","title":"Zohydro ER","class":"pdufa"}],
    template: '<div class="clndr-controls">
              <div class="clndr-previous-button">&lt;</div>
              <div class="clndr-next-button">&gt;</div>
              <div class="current-month"><%= month %> <%= year %></div>

            </div>
            <div class="clndr-grid">
              <div class="days-of-the-week clearfix">
                <% _.each(daysOfTheWeek, function(day) { %>
                  <div class="header-day"><%= day %></div>
                <% }); %>
              </div>
              <div class="days">
                <% _.each(days, function(day) { %>
                  <div class="<%= day.classes %>" id="<%= day.id %>"><span class="day-number"><%= day.day %></span></div>
                <% }); %>
              </div>
            </div>
            <div class="event-listing">
              <div class="event-listing-title">EVENTS THIS MONTH</div>
              <% _.each(eventsThisMonth, function(event) { %>
                  <div class="event-item">
                    <div class="event-item-name"><%= event.title %></div>
                    <div class="event-item-location"><%= event.location %></div>
                  </div>
                <% }); %>
            </div>'
});
```

#### Expected Behavior
Should not error and should render the provided template.

#### Your Environment

* Version used: 1.4.4
* Browser Name and version: Firefox 48b5
* Operating System and version (desktop or mobile): macOS 10.11.5
* Link to your project:

**Comment by mikegioia** [comment]
@tobz-nz I can't seem to recreate this one. The template you have looks fine and when I run it with a basic CLNDR instantiation it runs ok.

I can tell you though (and this might not be your error) that you can't define a JS string that way, but instead need to suffix each line with "/" or use string concatenation. But everything here looks good.

If you can recreate this in an environment like JSBin or JSFiddle then I can step into it further.

**Comment by tobz-nz** [comment]
Hi Mike, I got it going by hard-coding the string using backtick's (``` ` ```) to wrap the template string. So seems it was some issue with loading the template from the DOM. I can't think or figure out why it was breaking. but this solution works, so meh - I'll go with it. :)
