### ISSUE TITLE
Wrong date format

### ISSUE THREAD

**Issue by PhpSriptKiddie** [kylestetz/CLNDR#273]
Hey there.

I am using a danish locale (da.js) which defines L : 'DD/MM/YYYY' and translates everything into danish.

However, when I'm adding an event to my object array, the date is interpreted as MM/DD/YYYY instead - showing up in the wrong month of the calender.

How do I fix this?

**Comment by mikegioia** [comment]
@PhpSriptKiddie Do you know which locale the moment library is using? CLNDR depends on Moment.js and uses an instance throughout. It _should_ autodetect your Danish locale, but you can always inject a localized copy of moment (configured by you) into CLNDR.

In the options when you instantiate CLNDR, you can pass it in like this:

```
$( '.element' ).clndr({
    ...
    moment: yourMomentObject
});
```

**Comment by PhpSriptKiddie** [comment]
Thanks a lot for your answer. I have just tried doing as you described, but that throws me an error: clndr.js:1555 Uncaught TypeError: moment is not a function. The line in questions is the following:

`moment(events[i][multiEvents.singleDay]);`

I initalized my moment object like this:

`var momObj = moment.locale("da");`

**Comment by PhpSriptKiddie** [comment]
Upon updating to newest versions of clndr and moment, I get the following error instead:

`Uncaught TypeError: b is not a function`

from clndr.min.js

**Comment by mikegioia** [comment]
Can you paste your entire configuration lines? I just want to see what object you're passing in to the `moment` config parameter. (You have it commented out FYI).

**Comment by PhpSriptKiddie** [comment]
This is my entire code at the moment. The PHP code in the middle is just adding events that have been filled in with WordPress Advanced Custom fields:

```
<script>
var clndr = {};

var events = []

var momObj = moment.locale("da").format('L');

</script>

<?php while(the_repeater_field('aftaler')):
	if (get_sub_field('flere_dage')) {
	echo "<script>events.push({ end: '".get_sub_field('slutdato')."', start: '".get_sub_field('dato')."', title: '".get_sub_field('aftale')."' });</script>";
	}
	else {
	echo "<script>events.push({ date: '".get_sub_field('dato')."', title: '".get_sub_field('aftale')."' });</script>";
	}
endwhile;
?>

<script>



$( function() {	

  clndr = $('#my-clndr').clndr({
    template: $('#my-clndr-template').html(),
    events: events,
    multiDayEvents: {
        endDate: 'end',
        singleDay: 'date',
        startDate: 'start'
    },
    forceSixRows: true,
    moment: momObj
  });

});
```

**Comment by mikegioia** [comment]
You might have more luck at StackOverflow, but the answer could be here somewhere: http://momentjs.com/docs/#/use-it/require-js/

I think what you're storing in momObj is not the moment object. Could you try `var momObj = moment.locale("da")` instead? I think that might help it.

**Comment by PhpSriptKiddie** [comment]
I have tried both forms of momObj - both the one I'm using, and the one you propose. Unfortunately, none of them works :-/

**Comment by PhpSriptKiddie** [comment]
I managed to solve most of my problem by inserting the dates in MM/DD/YYYY format. Now they are shown correctly in the calender, but I need to change the format in the 'events this month' box.

When I do the following:

             ```
 <% _.each(eventsThisMonth, function(event) { %>
                  <div class="event-item">
                    <div class="event-item-name"><%= event.title %></div>
                    <div class="event-item-date"><%= moment(event.date).format('L') %></div>
                    <div class="event-item-date"><%= moment(event.start).format('L') %> <%= moment(event.end).format('L') %></div>
                  </div>
                <% }); %>
```

Everything is shown correctly. However, I only need to show only one of the #event-item-date div's. I don't really understand the whole <% annotation, but can I somehow implement an if-check that checks whether the event is a single or multi-day event, and only show the corresponding date? For now, the current date is shown for empty instances of event.date, event.start and event.end.

Thanks!

**Comment by krokofant** [comment]
As per the momentjs docs one should change the global locale like `moment.locale('da')` which is not to be used as a moment object. Instead the method is used to just set the locale globally then you'd use the global `moment`.

If you want a local version to just pass onto clndr then you could use:
```js
var momObj = moment().locale('da')
// ...
$('#my-clndr').clndr({
    template: $('#my-clndr-template').html(),
    events: events,
    multiDayEvents: {
        endDate: 'end',
        singleDay: 'date',
        startDate: 'start'
    },
    forceSixRows: true,
    moment: momObj
  });
```
Different from the @mikegioia suggestion is only the `()` efter moment.

**Comment by mikegioia** [comment]
I'm going to close this out, but perhaps the docs could be updated to make this clearer?
