### ISSUE TITLE
Get next date with events

### ISSUE THREAD

**Issue by extravaganza47** [kylestetz/CLNDR#275]
Hi,

I've been wondering if it's possible to get and display the next date with events?

Ex: 
"The next event will be on 2016-08-30"

Thanks.

**Comment by mikegioia** [comment]
Sorry @extravaganza47 you can't, but you are free to implement that in your template.

Also, for the future this issues list unfortunately is only for bugs :) https://github.com/kylestetz/CLNDR#submitting-issues
