### ISSUE TITLE
Can 1 calendar use multiple templates?

### ISSUE THREAD

**Issue by Brugman** [kylestetz/CLNDR#278]
Desired layout: http://i.imgur.com/OhUAtqS.png

The month view and list view are separated. Can this be done with one CLNDR? Wrapping the entire row with the text/template script tag didn't work.

If not I'll run multiple with the same source and combine the prev/next buttons as mentioned in #40 & #46.

**Comment by kylestetz** [comment]
One calendar instance won't support two different templates, so your best bet is to use two clndr instances with some shared event handling to make sure both calendars move in sync with each other.

I would suggest saving the clndr instances (e.g. `var eventsView = $('#events-view').clndr({ ... })`) and making previous/next button event handlers that call `.previous()`/`.next()` on both of them together. Clndr provides automatic event handling if you choose to use it, but in this case you're better off handing those outside of the plugin.

:+1:
