### ISSUE TITLE
eventsThisDay

### ISSUE THREAD

**Issue by Captain-GaDo** [kylestetz/CLNDR#280]
Do you have a "eventsThisDay" function? I want to list all the available hours in X day when i click it on the calendar.

Thanks

**Comment by mikegioia** [comment]
@Captain-GaDo Unfortunately we do not, but you can achieve what you want with your template.

Also, the issues here are only for bugs :)  https://github.com/kylestetz/CLNDR#submitting-issues

**Comment by schester44** [comment]
This feature should be implemented.
