### ISSUE TITLE
Scrollable "Events this month" list

### ISSUE THREAD

**Issue by rafaelhc** [kylestetz/CLNDR#283]
I do not have a bug report, but would like to ask for guidance for a specific functionality, using CLNDR.

I would love for the "Events this month" to be a scrollable list, containing all your events (Jan to Dec). When you for example scroll from an event that is in September to an event in October, the calendar would change month accordingly. When changing month in the datepicker itself, you would anchor down to the first event of that month in the "Events this month".

Sort of the functionality that I am hoping for: https://dribbble.com/shots/2843999-Snowbird-Event-Calendar-V1

Do you think such a functionality is possible using CLNDR?

Thanks.

**Comment by mikegioia** [comment]
Sorry @rafaelhc the issues here are only for bugs. We sadly don't have time to give feedback or answer implementation questions :( You might have more luck at Staff Overflow.
