### ISSUE TITLE
Previous month dates are broken with momentjs 2.17.0

### ISSUE THREAD

**Issue by GreatWizard** [kylestetz/CLNDR#288]
Some dates are broken with the last version of momentjs (2.17.0).
I have `NaN` dates for date in the previous month.

#### Context
After digging a bit, I found this patch in the momentjs library in the 2.17.0 changelog:
https://github.com/moment/moment/pull/3506/files#diff-e792da0601bb2705000e86ef203f8e73R64

#### Expected Behavior
Correct dates of the previous month.

#### Actual Behavior
Date of the previous month are `NaN`.

#### Possible Fix
The date sent to momentjs looks like not valid for the previous month.
Probably, because we use this syntax `[currentYear, CurrentMonth, negativeDay]`.
The negativeDay sounds hacky, we should try to use `subtract` function like `moment([currentYear, CurrentMonth, 0]).subtract('dayToRemove')`.

#### Steps to Reproduce
* Update momentjs to 2.17.0
* or go on http://momentjs.com and in the console type: `moment([2014,2,-2]).isValid()`

#### Your Environment
* Version used: 1.4.6

**Comment by kylestetz** [comment]
Closed with #289. Thanks!
