### ISSUE TITLE
v1.4.7 has not been published to npm

### ISSUE THREAD

**Issue by dpoindexter** [kylestetz/CLNDR#290]
#### Expected Behavior
`npm install clndr` installs v1.4.7

#### Actual Behavior
`npm install clndr` installs v1.4.6

`npm info` only shows versions up to 1.4.6, so it looks like 1.4.7 just needs to be published.

**Comment by mikegioia** [comment]
Just updated it: https://www.npmjs.com/package/clndr

**Comment by kylestetz** [comment]
My fault! Sorry! Lost the commit checklist I used to keep around 😬
