### ISSUE TITLE
30x performance improvement on target.events filter function

### ISSUE THREAD

**Issue by alexalexalex-s** [kylestetz/CLNDR#294]
I think you can dramatically improve the speed of the `filterFn` within the `buildTargetObject` method by using a date intersect check instead of `isSameStart`, `isAfterStart`, `isSameEnd` and `isBeforeEnd`.

The relevant code is on line 1006. On an events list of 3000, the current code completes the filter in around 130ms vs the intersect code at around 4ms. I might've missed something, but so far in testing it works 100%.

Current code:
```
var filterFn = function () {
    var isSameStart = target.date.isSame(
        this._clndrStartDateObject,
        'day');
    var isAfterStart = target.date.isAfter(
        this._clndrStartDateObject,
        'day');
    var isSameEnd = target.date.isSame(
        this._clndrEndDateObject,
        'day');
    var isBeforeEnd = target.date.isBefore(
        this._clndrEndDateObject,
        'day');
    return (isSameStart || isAfterStart)
        && (isSameEnd || isBeforeEnd);
};
```

Improved code:
```
var targetEndDate = (target.date) ? target.date.clone().endOf("day") : null;
var filterFn = function () {
    return (this._clndrStartDateObject <= targetEndDate
        && target.date <= this._clndrEndDateObject);
};
`````

**Comment by alexanderschana** [comment]
The same intersect can also be applied in the `Clndr.prototype.createDayObject` method.

Using a list of 3000 events, the original render time was over 2 seconds, using the intersect it's down to 200ms.

In the monthEvents loop, replace:
`if ( (day.isSame(start, 'day') || day.isAfter(start, 'day'))
                && (day.isSame(end, 'day') || day.isBefore(end, 'day')) )
            {
                eventsToday.push( monthEvents[j] );
            }`

with
`if (start <= dayEnd && day <= end) {
                eventsToday.push(monthEvents[j]);
            }`

The dayEnd variable is: `var dayEnd = day.clone().endOf('day');`, set before the loop starts.

(My apologies if I've missed something!)

**Comment by kylestetz** [comment]
This sounds interesting @alexanderschana — want to put together a PR?

**Comment by mikegioia** [comment]
I'm going to bring this back and re-submit as a new PR. I went through the proposal and it looks sound.

**Comment by mikegioia** [comment]
PR at #341 , I'll re-surface that this weekend and hopefully merge it in shortly after.

**Comment by mikegioia** [comment]
@alexalexalex-s Thank you again for your help, this has finally made it's way into production with #341. I'm going to close this one out.
