### ISSUE TITLE
Next Month Not Work

### ISSUE THREAD

**Issue by ebadgh** [kylestetz/CLNDR#300]
When i using mini-calendar in my computer or on your official website, and click on Next month button, my Browser get hanged and can't run next month calendar.

I use Firefox Windows Latest Version

**Comment by mikegioia** [comment]
This needs to follow the new issue template

**Comment by ebadgh** [comment]
This issue is clear bug of script that didn't need any more explain

**Comment by criztovyl** [comment]
I can't reproduce on FF ESR (45.7.0) on Debian Stretch, it's not that simple.

**Comment by mikegioia** [comment]
When submitting issues it needs to follow the format that we've set up.
