### ISSUE TITLE
for..in loop crashes on months object array

### ISSUE THREAD

**Issue by manojkalaivanan** [kylestetz/CLNDR#301]
#### Where is the bug? 
[Here](https://github.com/kylestetz/CLNDR/blob/master/src/clndr.js#L749-L751).

#### Description: 
`for...in` iterates over all enumerable properties, not just the array's elements ([Ref](http://adripofjavascript.com/blog/drips/the-problem-with-for-in-and-javascript-arrays.html)). 

 In our use case, We have a function `move` attached to all the Array objects. `for..in` iterates not just on the indices of `months` array but also on this function and crashes. 

#### Expected Behavior
The loop iterating on the `months` array shouldn't crash.

#### Actual Behavior
![clndr-js-for-in-bug](https://cloud.githubusercontent.com/assets/6604021/22944561/f2e92a0a-f2a5-11e6-8461-e49348e0f527.gif)

#### Possible Fix
Replace the `for..in` loop [here](https://github.com/kylestetz/CLNDR/blob/master/src/clndr.js#L749-L751) with a simple for loop. 

```
for (i = 0; i < months.length; i++) {
    numberOfRows += Math.ceil(months[i].days.length / 7);
}
```
#### Steps to Reproduce
1.  set 
``` Array.prototype.voice = "James Earl Jones";```
2.  Try to load more than a month.
```
 lengthOfTime: {
     months: 2,
     interval: 2
    }
```
3. Observe the crash.

#### Your Environment
* Version used:  1.4.6
* Browser Name and version: Chrome (56.0.2924.87)
* Operating System and version (desktop or mobile): Desktop and Mobile

**Comment by mikegioia** [comment]
@manojkalaivanan I like this and I appreciate you filling out the bug form. My last ask is if you could submit this fix as a PR?

**Comment by manojkalaivanan** [comment]
@mikegioia Done. Here is the PR https://github.com/kylestetz/CLNDR/pull/302.
Thanks!

**Comment by mikegioia** [comment]
Merged into master
