### ISSUE TITLE
Different calendar view in different browsers

### ISSUE THREAD

**Issue by MichaelRosmane** [kylestetz/CLNDR#303]
### Context
I'm using CLNDR to display a booking overview for a property rental place. I populate an array with booked dates when loading the page and use that array to display days green/red in 3 CLNDR instances, each showing a different month. The 3 instances are using the same events. 

The 3 instances are linked by monthchange events to change accordingly when 1 changes. 

Any pointers as to where to look to resolve this, would be highly appreciated.  If you need more information, just say so, I'll gladly include it.

#### Expected Behavior
Accross all browsers, the clndr instances should have the same events in the 'evensThisInterval' property when viewing the same month.

#### Actual Behavior
In chrome & firefox, the calender displays correctly, in IE (version: 11) & Safari, it only displays certain dates, and has a subset of all event dates set when viewing 'evensThisInterval'. 

Screenshots:
console log output in chrome: https://www.dropbox.com/s/59o7ctqxt9351zc/sunset-in-spain-issue-screenshot-chrome.JPG?dl=0
console log output in IE: https://www.dropbox.com/s/whk7b3zb6bryujj/sunset-in-spain-issue-screenshot-ie.JPG?dl=0

#### Steps to Reproduce
https://sunsetinspain.com/properties/luxurious-penthouse-golf-resort-las-colinas-2-bedr-2-bathr-roofterrace-4-sleeps/

On the link above, the 3rd tab (availability) shows 3 linked calenders indicating when a property is available or not. When changing months, the first calendar is dumped to the console.

In Chrome & firefox, when viewing the 'evensThisInterval' iit displays the correct events in the console log. in IE (version: 11) & safari it does not. 

1) go to link above
2) open tab 'availability'
3) change month to trigger console output
4) in chrome & firefox, 'evensThisInterval' shows correct events, in IE (version: 11) & safari, it does not

#### Your Environment
* Version used: 1.4.7

**Comment by mikegioia** [comment]
Thanks for the detailed report @MichaelRosmane. I appreciate this, however we can't debug code like this because I can't access it, modify it, or guarantee that this isn't a dependency issue or mistake.

If its possible, can you recreate this in a JSFiddle? We need to remove all possible dependencies to confirm that it's in fact a bug and not something else. The suggested way to stage this would be to create an events array like you have, and pass it to CLNDR and then output the eventsThisInterval.

**Comment by MichaelRosmane** [comment]
I'll look into setting up a fiddle first thing tomorrow. Thanks for getting back to me so quickly.

**Comment by MichaelRosmane** [comment]
As promised: [FIDDDLE](https://jsfiddle.net/michaelrosmane/upo75fqw/5/)

I used the cldnr, jquery, underscore & moment files used on the actual project. I also added some minor styling to visually illustrate the issue. 

As you asked, the first calendar drops the 'eventsThisInterval' to console on each month change. 

if you need any further information, please let me know.

**Comment by mikegioia** [comment]
At first glance the only config issue I notice is that you have multi-day events enabled but no startDate or endDate properties on any of the events. That shouldn't matter for this problem though.

I see moment is throwing some errors, which may or may not be related, but I notice that `eventsThisInterval` always contains all 52 events on every month. It also doesn't appear that any of these events are triggering the calendar to give the "event" class to any of the days. (This also leads me to believe it might be a moment() issue).

If you're able to you, could you add some logging into the CLNDR library locally on your computer at this code block: https://github.com/kylestetz/CLNDR/blob/master/src/clndr.js#L430-L440

This is the part that builds the `eventsThisInterval` array and my hunch is that in IE/Safari this is failing for some reason.

I hate to ask this as well, but is it possible to use CDN versions of the external dependencies, and only render one calendar with no more than 10 total events? I just want to see if we can get CLDNR showing any days as having events in Safari/IE.

**Comment by MichaelRosmane** [comment]
Ah, something I failed to mention earlier, when you go all the way to october, IE & safari do show events that are correct, but that made it even stranger to me as why it wouldd only show a small subsit of events. 

Anyway... I'll look into adding the externals through CDN, downsizing the example & adding the extra logging. 

I'll post a new fiddle when i'm ready...

**Comment by MichaelRosmane** [comment]
@mikegioia new [fiddle](https://jsfiddle.net/michaelrosmane/upo75fqw/13/) 

I added CDN for jquery, underscore & moment, clndr has extra logging in the block you asked for, and is hosted on server where project itself is hosted. 

Also downsized the list of events to about 10 & removed everything but 1 calendar.

**Comment by mikegioia** [comment]
Thanks @MichaelRosmane I should be able to check this out in the afternoon.

**Comment by mikegioia** [comment]
@MichaelRosmane Ah I figured it out I think, it's the date format. If you change the months from "2016-4-10" to "2016-**04**-10" It should work. You'll need to format the months to always have 2 numbers, it seems to cause problems in IE/Safari. This explains the moment() deprecation warning in the console too.

**Comment by MichaelRosmane** [comment]
Ah that would also explain why october does display it's events. 

I added the leading zeroes & the issue is resolved. Thanks for helping me figure it out!

Also thanks a lot for the swift follow-up.
