### ISSUE TITLE
Event list sorting

### ISSUE THREAD

**Issue by luchorengo** [kylestetz/CLNDR#308]
Hi, excellent plugin! 
Just wondering if it's possible to change the sort order in events list. I'd like to have them ordered by date ASC instead of date DESC like it's now.

Regards

**Comment by mikegioia** [comment]
Hi @luchorengo, I think you can sort the events before they go into CLNDR. It should retain the same ordering.

Unfortunately this issues list is for bugs only. However if you find you're feature request is not satisfied by CLNDR, we are more than open to accepting PRs!
