### ISSUE TITLE
Update website with full set of options from github documentation

### ISSUE THREAD

**Issue by palerdot** [kylestetz/CLNDR#310]
[Plugin Website](http://kylestetz.github.io/CLNDR/) does not include all the possible options mentioned in the github repo. It is very confusing as lots of options is missing in the website.

#### Expected Behavior

The website should mirror the full set of options from github and viceversa

#### Actual Behavior

Website has only few options listed. Lots of important options are missing like `selectedDate`, `trackSelectedDate`

**Comment by mikegioia** [comment]
@palerdot I'd love a PR for this but sadly it would take a good amount of effort to make that happen :(

I'm going to mark this as closed as it's not a bug with the library and we're using this issues list for bugs only.

**Comment by palerdot** [comment]
@mikegioia let me see if I can come up with a pull request for fixing this issue.

**Comment by criztovyl** [comment]
Just a quick side-note...

> I'm going to mark this as closed as it's not a bug with the library and we're using this issues list for bugs only.

I think an issue with the documentation is similar to a bug in the library itself so it shouldn't be closed yet. (In contrast to Q&A, which really is not a bug.)
