### ISSUE TITLE
Week numbers

### ISSUE THREAD

**Issue by fractalf** [kylestetz/CLNDR#312]
Is there any way to get week numbers (1, 2, .. 52..) into the calendar?
Would be great with these settings:
```
lengthOfTime: {
    months: null,
    days: 7,
    interval: 7
}
```

**Comment by mikegioia** [comment]
@fractalf Please check the docs/Readme, you can do that in your template :)

**Comment by fractalf** [comment]
@mikegioia Thank you for a quick response! :)
I have scanned the docs/Readme several times on this already, are you sure it contains any information about how to the the **week number** ? Did you mean by using the moment lib?
I know it contains the *lengthOfTime* which I used as an example above, but not how to get the week number..

**Comment by mikegioia** [comment]
Yea, unfortunately that's just the day of the week's name in there :( You would need to use the moment object in `intervalStart` I think.
