### ISSUE TITLE
Repeated days

### ISSUE THREAD

**Issue by Erick-Zanetti** [kylestetz/CLNDR#313]
When creating the calendar in the month of October is repeating some day in every year, what could cause this.

![img_7801](https://user-images.githubusercontent.com/29898441/31249061-53beb554-a9ec-11e7-9275-b2f12934d6ac.JPG)

![img_7802](https://user-images.githubusercontent.com/29898441/31249060-53bdbdac-a9ec-11e7-887b-1346c000f56e.JPG)

![img_7803](https://user-images.githubusercontent.com/29898441/31249059-53bd8ce2-a9ec-11e7-8baf-ff035d650a9e.JPG)

This happens only in the month of October and in iphones, desktop and android works normally

**Comment by leandrodiniz** [comment]
Same here, it's happening on Safari and Firefox. It's look like an old issue: #196 

Maybe, Airbnb is using the same plugin 😄 

![image](https://user-images.githubusercontent.com/1706703/31322713-6e3a0e7c-ac73-11e7-8c3e-5c488c18bab0.png)

**Comment by mikegioia** [comment]
Thanks for the updates. I think this is a bug in the Moment library :( Unfortunately I don't have time this week or next to really debug it.

**Comment by Erick-Zanetti** [comment]
I solved this problem including a for to check if there is repeated data and play to the end of the array, bet with invisible session css days after 31. Not the perfect solution but can help you.

**Comment by Erick-Zanetti** [comment]
I solved using a for to compare the dates and check the repeated and place to the end of the list, and with css hidden the days that are not part of the month. Not is the perfect solution but help
