### ISSUE TITLE
Multi day event, but not in a row.

### ISSUE THREAD

**Issue by DasPartyEinhorn** [kylestetz/CLNDR#323]
Hi, 
I really like this Plugin, it was so easy to implement a calendar for my needs. 

But there is one feature left I'm missing. I would like to insert events that can occour on multiple days, but not in a row. More like a seminar that takes places in march and in september. 
Of course I could insert them as two events, but when the dates lie in the same month the event gets listed double on the eventlist. 

Does someone know a solution to show them in the eventlist only once but mark every date in the calendar ? 

Maybe this should be labeled as enhancement or change request.

**Comment by mikegioia** [comment]
Thanks at @DasPartyEinhorn, unfortunately there are no plans to build this but I'll tag it enhancement for the future.
