### ISSUE TITLE
It's possible to move self.options.clickEvents.click.apply(self, [target]); after setting the selected date?

### ISSUE THREAD

**Issue by waltercruz** [kylestetz/CLNDR#332]
#### Context
Hi! I'm trying to get the current selected date on click event on calendar, using the clickEvents. But, the hook defined on clickEvents is called before setting the selectedDate, so the behaviour is that I don't get the selectedDate.

#### Expected Behavior
this.options.selectedDate should be reliable to get on clickEvents.click

#### Actual Behavior
this.options.selectedDate is erratic (doesn't work on first click)

#### Possible Fix
move the section:

            if (self.options.clickEvents.click) {
                target = self.buildTargetObject(event.currentTarget, true);
                self.options.clickEvents.click.apply(self, [target]);
            }

after setting the selectedDate.

#### Steps to Reproduce

https://codepen.io/waltindead/pen/oyJdoN?editors=1111

1. click on one of the dates
2. at the first click, options.selectedDate is null

#### Your Environment

* Version used: 1.4.7
* Browser Name and version: Chrome 67.0.3396.99
* Operating System and version (desktop or mobile): Mac OS X 10.12.6
* Link to your project: https://codepen.io/waltindead/pen/oyJdoN

**Comment by mikegioia** [comment]
Thank you @waltercruz , I'm going to try and run through / test this one out today. I appreciate the detailed and well-formatted write up :stuck_out_tongue:

**Comment by mikegioia** [comment]
This is updated in a new release PR over at #340
