### ISSUE TITLE
Have multiple classes for an events such as a class for a bank holiday and school holiday class

### ISSUE THREAD

**Issue by LukeAtwill92** [kylestetz/CLNDR#335]
Context
I'm looking to add multiple classes depending on the type of event i am i am assigning the date. But it is only taking the first class it reads and adding this to all dates.

Expected Behavior
To have a different class for each event type, one for bank holidays and one for school holidays.

Actual Behavior
Only uses the first class from the first date and assigned that to all events

Code Below 
`if($('#calendar')) {
	var dates;
	if (dates === undefined) {
	    
	} else {
		var arrayLength = dates.length;
		for (var i = 0; i < arrayLength; i++) {
		    var datetype = dates[i].type;
			if(datetype == 'school-holiday') {
				var typeClass = 'mw-event-school';
			} else {
				var typeClass = 'mw-event-bank';
			}
			$('#calendar').clndr({
				events: dates, 
				multiDayEvents: {
					endDate: 'endDate',
					startDate: 'startDate',
					title: 'title',
					type: 'type'
				},
				classes: {
					past: "my-past",
					today: "my-today",
					event: typeClass, 
					inactive: "my-inactive",
					lastMonth: "my-last-month",
					nextMonth: "my-next-month",
					adjacentMonth: "my-adjacent-month",
				} 
			});
		}
	}
}`

**Comment by JulianHodor** [comment]
Hey, don't know if this is still relevant, but i just stumbled upon the same problem. I would suggest another method:

Assuming you have your events list like this:

var eventslist = [
      {
    date: "2018-08-28",
    title: "Title",
    type: "event-type"
    }
];

you could use the "doneRendering" callback and attach a function adding your event-type as css classes to your calendar:

        doneRendering: function () {

          var arrayLength = eventslist.length;
          for (var i = 0; i < arrayLength; i++) {
            mydate = eventslist[i].date;
            mytype = eventslist[i]. type;
            $('td.calendar-day-'+mydate+'').addClass(mytype);
          }

        }

This way you can easily add custom classes for different event types. Also other values could be attached to calender dates (data fields e.g.).

**Comment by nk9** [comment]
Thanks a bunch to @JulianHodor for the idea. I've taken this approach, but I needed to have it work for both single-day and multi-day events. I used [moment-range](https://github.com/rotaready/moment-range#by) to iterate dates of multi-day events, although [it's possible to do it with vanilla moment](https://stackoverflow.com/a/59901201/1749551) as well. Here's the code I ended up with:

```
function doneRendering() {
	// Add event type classes
	for (let event of this.options.events) {
		// Single-day events
		if (event.date) {
			mydate = event.date;
			mytype = event.type;
			$('.day.calendar-day-'+mydate+'').addClass(mytype);
		}

		// Multi-day events
		else {
			const range = moment.range(event.start, event.end);

			for (let day of range.by('day')) {
				mydate = day.format('YYYY-MM-DD');
				mytype = event.type;
				$('.day.calendar-day-'+mydate+'').addClass(mytype);
			}
		}
	}
}
```

Then, just add types to your events and pass the above method when initializing your clndr object.
```
$('#mycal').clndr({
// etc.
	events: [
		{
			title: 'Birthday party',
			date: '2020-09-24',
			type: 'birthday'
		}, {
			title: 'Holiday',
			date: '2020-07-04',
			type:  'holiday'
		}, {
			title: 'Finals',
			start: '2020-06-06',
			end:   '2020-06-12',
			type:  "finals"
		}
	],
	doneRendering: doneRendering
});
```
