### ISSUE TITLE
Feature Request: Multi-day select

### ISSUE THREAD

**Issue by bgp1** [kylestetz/CLNDR#336]
I'd like the ability to be able to select multiple days at the same time. I'm thinking if [shift] is held down on select it doesn't do the default action but instead allows multiple dates to be selected. I was thinking only a range (think like 1st-5th) and not 1st, 3rd, 5th as the former sounds easier to accomplish.

**Comment by mikegioia** [comment]
Thanks @bgp1, we're only using these issues for bug reports right now, but I'll log this on the future to-do list. I think the absolute fastest way to get this up would be to submit a PR.
