### ISSUE TITLE
set month and year same time

### ISSUE THREAD

**Issue by rameshkithsiri** [kylestetz/CLNDR#337]
How to change month and year in the same time?
I am currently using
```
calendar.setYear(year);
calendar.setMonth(month);
```
But i have an ajax event on `doneRendering`. When I change the days with above codes it loads ajax data two times.
I want a function similiar to `setYearAndMonth`

**Comment by jaydeept4f** [comment]
Hello @mikegioia ,

I have one small question.

How can I `setMonth()` and `setYear()` without rendering ?

Thanks in advance.

**Comment by mikegioia** [comment]
@jaydeept4f The calls to setMonth() and setYear() both call render() from within them. There's no real way to do that unfortunately.
