### ISSUE TITLE
"Na" being displayed instead of previous month's dates

### ISSUE THREAD

**Issue by Blackbaud-KimberlyHammer** [kylestetz/CLNDR#338]
#### Issue Being Reported
Notice that at the beginning of the month, the previous month's dates are showing as "Na" instead of the date. At the end of the month, the next month's dates are displaying properly.

![image](https://user-images.githubusercontent.com/7794396/52904432-3c9cba00-31fa-11e9-9e70-8c7d3c0add81.png)

#### Expected Behavior
I would expect the dates for the previous month to display correctly, like they do for the next month.

#### Steps to Reproduce
1. Go to https://indiana-al-anon.org/events/event-calendar/ or https://indiana-al-anon.org/ and notice the issue described above on the calendars.
2. Click > to forward to the next month and notice it happens for all months whose first day of the month does not fall on Monday.

#### Your Environment
* Version used: Event CLNDR Version 1.05
* Browser Name and version: Chrome Version 72.0.3626.96 and Firefox Version 65.0
* Operating System and version (desktop or mobile): desktop version on macOS High Sierra 10.13.6, it also occurs on iPhones

**Comment by gjwmvg** [comment]
Dear Blackbaud-KimberlyHammer,
it might be user fad115 found a solution for your problem. Look at [https://wordpress.org/support/topic/nan-in-adjecant-month-fix/](url)

**Comment by mikegioia** [comment]
@Blackbaud-KimberlyHammer If this is still an issue for you, would you please mind doing the following things for me:

1. Upgrading to the latest version of clndr (1.4.9 right now)
2. Provide a configuration example directly on this issue.

I believe you that it's not working on your site but I'll need config to test with on my machine, and to be able to reproduce the error for testing.

**Comment by mikegioia** [comment]
Closing this since it seems stale.
