### ISSUE TITLE
Styling/CSS Not showing

### ISSUE THREAD

**Issue by KidA001** [kylestetz/CLNDR#346]
#### Context
I'm using the Full Calendar Template from the first calendar on the http://kylestetz.github.io/CLNDR/ page, but do not see any styling. I'm unclear if I'm doing something wrong, or if no styling is included in the NPM package. Any help appreciated.

#### Expected Behavior
Expected to see styling similar to the first calendar at the top of http://kylestetz.github.io/CLNDR/

#### Actual Behavior
No styling, see screenshot below
![image](https://user-images.githubusercontent.com/8673088/70378938-ae560980-18db-11ea-877b-b85252e22483.png)

#### Steps to Reproduce
**HTML**
```html
<html>
  <head>
    <title>Welcome</title>

    <link rel="stylesheet" media="all" href="/assets/application.debug-8f0ab06df214da85f20badd5140ad9071c25a2186b569d896dbf0f00ebbd5acd.css" data-turbolinks-track="reload">
  </head>

  <body>
    <h2>Hello World</h2>
    <div id="full-clndr"></div>

    <script src="/js/welcome.js"></script>
  </body>
</html>
```

**welcome.js**
```javascript
import moment from "moment";
import $ from "jquery";
import _ from "lodash";
require("clndr");

document.addEventListener("DOMContentLoaded",function(){
  let clndr = {};
  const currentMonth = moment().format('YYYY-MM');
  const nextMonth    = moment().add(1, 'month').format('YYYY-MM');
  const events = [
    { date: currentMonth + '-' + '10', title: 'Persian Kitten Auction', location: 'Center for Beautiful Cats' },
    { date: currentMonth + '-' + '19', title: 'Cat Frisbee', location: 'Jefferson Park' },
    { date: currentMonth + '-' + '23', title: 'Kitten Demonstration', location: 'Center for Beautiful Cats' },
    { date: nextMonth + '-' + '07',    title: 'Small Cat Photo Session', location: 'Center for Cat Photography' }
  ];

  clndr = $('#full-clndr').clndr({
    template: $('#full-clndr-template').html(),
    events: events,
    forceSixRows: true
  });
});
```

#### Your Environment
"clndr": "^1.5.1",
"jquery": "^3.4.1"
"lodash": "^4.17.15"
"moment": "^2.24.0"
"@rails/webpacker": "^4.2.0"
* Browser Name and version: Chrome Version 78.0.3904.108
* Operating System and version (desktop or mobile): Desktop Mac OSX Mojave
* Link to your project: (running locally)

**Comment by mikegioia** [comment]
@KidA001 Clndr doesn't come with any CSS or styling. The demo that you linked to uses custom styling that Kyle put together for that demo. All CSS and styling is left to the developer to do.

**Comment by KidA001** [comment]
@mikegioia I'm really bad at CSS, do you think we can get Kyle to style the calendar for my application?

**Comment by mikegioia** [comment]
@KidA001 :D I doubt it but if you want something to start with, you can copy the CSS we use in the demo into your application. In this file, https://github.com/kylestetz/CLNDR/blob/master/demo/css/clndr.css#L62, lines 62 through 221 contain the styles for the large calendar (i.e. `.cal1`). You can see the mini-calendar styles are in there under `.cal2`. If you look at the source or with the web inspector you'll see how cal1 is applied to the template and all that.
