### ISSUE TITLE
Mixing recurring with single day events

### ISSUE THREAD

**Issue by MarianArlt** [kylestetz/CLNDR#41]
I first tried this in my personal project but tested it with your example file and it's easy to reproduce. Recurring events are shown just fine, but adding a single day event to the eventArray would trigger the actual day (today) to get the "event" class applied and not show the event on the given date at all.

I tried this with your example site.js:

```
  var eventArray = [
    { startDate: thisMonth + '-03', endDate: thisMonth + '-08', title: 'Multi-Day Event' },
    { startDate: thisMonth + '-21', endDate: thisMonth + '-23', title: 'Another Multi-Day Event' },
    { date: '2013-11-25', title: 'Ow Mah Gawd Single Day'}
  ];
```

By deleting the **multiDayEvents** option the single event is shown again.
By deleting all recurring events from the eventArray the "event" class is withdrawn from the actual day (today)
With the multiDayEvents option defined, the described behavior triggers even if there are no recurring events given yet

**Comment by kylestetz** [comment]
For anyone stumbling upon this issue, as of v1.2.7 clndr supports mixing multi- and single-day events using the new `multiDayEvents.singleDay` property as described in the [documentation](https://github.com/kylestetz/CLNDR#multi-day-events).
