### ISSUE TITLE
Push unique class to Events day

### ISSUE THREAD

**Issue by bent10** [kylestetz/CLNDR#58]
How to add a unique class to the event day?

``` html
<div class="day past calendar-day-2013-12-01" id="">1</div>
<div class="day past event my-event-class calendar-day-2013-12-02" id="">2</div>
```

or 

``` html
<div class="day past event start-event-class calendar-day-2013-12-02" id="">2</div>
<div class="day past event calendar-day-2013-12-02" id="">2</div>
<div class="day past event calendar-day-2013-12-03" id="">3</div>
<div class="day past event end-event-class calendar-day-2013-12-04" id="">4</div>
```

**Comment by pacoogle** [comment]
Hi @kylestetz in my case this code doesn't work :-( 

<div class="calendar-content clearfix">
		<% _.each(days, function(day,val) { %>
                    <div class="<%= day.classes %>" id="<%= day.events[0].type %>">
                         <div class="number"><%= val %></div>
                    </div>

<% }); %>
</div>


Javascript error -> type undefined BUT type is defined :-)!!! Help me please :-)
