### ISSUE TITLE
Marking events with different colors

### ISSUE THREAD

**Issue by kylestetz** [kylestetz/CLNDR#6]
Someone asked me this question directly and I thought it would be useful to post here for others to come across.

If you'd like to show your events with different colors, you'll need some way of distinguishing them within the event data. Let's say our event data has a `type`:

``` javascript
events = [
  { date: "2013-09-16", title: "Baseball Game", type: "sports" }
]
```

Now in my template I can ask what the event type is, or better yet I can just dump the event type out as a class and style it accordingly.

``` html
<div class="clndr-grid">
  <div class="days">
    <% _.each(days, function(day) { %>
      <div class="<%= day.classes %>" id="<%= day.id %>">
        <div class="number"><%= day.day %></div>
        <% _.each(day.events, function(event){ %>
          <div class="event <%= event.type %>"><%= event.title %></div>
        <% }) %>
      </div>
    <% }); %>
  </div>
</div>
```

Here each grid box contains a `<div>` for every event on that day. The class on the `<div>` is the event's type, which means I can now style `.sports { background-color: red; }` and specify other colors for other event types.

**Comment by gdvalderrama** [comment]
This is nice, but what if two events overlap?

**Comment by michelt** [comment]
Hey. This is cool. But how can I do the same thing at the days level (and not events) (I want a color for a day, independently from its events). Is it a good practice to extend the days array (day.color)? Or should I use the extra option (extra['2016-03-13']['color'])? Or am I missing something?

**Comment by archienorman11** [comment]
Thanks for sharing this. I was just wondering if its possible to achieve the same results by modifying the default template? I have shared my code [here](http://stackoverflow.com/questions/40358976/appending-a-class-to-a-javascript-calendar-given-the-data-clndr-js):  it would be greatly appreciated if anyone had any advice here.
