### ISSUE TITLE
Feature: Custom Date Ranges in the Template

### ISSUE THREAD

**Issue by kylestetz** [kylestetz/CLNDR#72]
@palodelincak brought up the point in issue #71 that creating a view in increments other than one-month-at-a-time is difficult, bordering on unreasonable.

I am going to move forward implementing an option that allows you to choose an arbitrary length of days to have available in the template. Here's what it could look like:

```javascript
$('#calendar').clndr({
  template: $('#template').html(),
  length: {
    days: 7
  }
});
```

Specifying `length.days` here tells clndr "I want you to give me 7 days at a time in my template". Thus the `clndr-next-button` will increment the data by 7 days instead of a month. I'm thinking there will be a different set of callbacks specific to this situation, perhaps `onNextIncrement` and `onPreviousIncrement`.

Specifying a concrete number of days doesn't work well if you want to show several months at a time, so:

```javascript
$('#calendar').clndr({
  template: $('#template').html(),
  length: {
    months: 3
  }
});
```

This would behave almost exactly like clndr does now, except that you would get three months in your template instead of one. Perhaps there are some template functions that would make sorting the days out into months a little easier.

Feedback is welcome as always- I'm pretty sure @sylouuu will have something to say about this!

**Comment by ikhan009** [comment]
Hi kylestetz
there is little confusion on mini calander.
1) how i set event for future date
2) there i want to show popup and user can select campaign and schedule on that date
3) when click on any event it show monthwise event, i need day wise event to show, down is 
screanshot.
http://screencast.com/t/GCEZLzksQzu

hope you will guide me.

**Comment by kylestetz** [comment]
Just realized I can close this! This feature was added in v1.2.11 thanks to the hard work of @mikegioia.
