### ISSUE TITLE
mouseOver to clndr events!

### ISSUE THREAD

**Issue by octameter** [kylestetz/CLNDR#73]
Hi!

I think it would be nice to have a possibility to mouseOver the days, as you would in click. Essentialy it would be a mere '$container.on('mouseover',...' etc.
=> one might consider renaming the clickEvents to a more general events.

I've used it and it is beautiful!
And by the way clndr is great!

**Comment by akashraj9828** [comment]
I am trying to add an on hover event which will get triggered when we hover over days but I am unable to make it work can you help me please ,let me know if i'm not implementing the code correctly.
`calendar = $('.cal1').clndr({           
 
       events: eventArray,
        template: clndrTemplate_with_badge,
        clickEvents: {
           ready: function() {
                var self = this;
                $(this.element).on('mouseover', '.day', function(e) {
                    var target = self.buildTargetObject(e.currentTarget, true);
                    console.log("hrl");
                });
                },
            click: function (target) {
               console.log('Cal-1 clicked: ', target);
            },
            today: function () {
                console.log('Cal-1 today');
            },
            nextMonth: function () {
                console.log('Cal-1 next month');
            },
            previousMonth: function () {
                console.log('Cal-1 previous month');
            },
            onMonthChange: function () {
                console.log('Cal-1 month changed');
            },
            nextYear: function () {
                console.log('Cal-1 next year');
            },
            previousYear: function () {
                console.log('Cal-1 previous year');
            },
            onYearChange: function () {
                console.log('Cal-1 year changed');
            },
            nextInterval: function () {
                console.log('Cal-1 next interval');
            },
            previousInterval: function () {
                console.log('Cal-1 previous interval');
            },
            onIntervalChange: function () {
                console.log('Cal-1 interval changed');
            }
            
        },
        showAdjacentMonths: true,
        adjacentDaysChangeMonth: false
    });`
