### ISSUE TITLE
Destroying an CLNDR.js instance / switch an option [branch: intervals]

### ISSUE THREAD

**Issue by nightgrey** [kylestetz/CLNDR#92]
Hello,

is there a way to destroy an CLNDR.js instance or switch an option and force a re-render of the calendar with other options? I'm stuck a bit.

I'm watching the browser viewport width with ````$(window).on('resize')```` and want to change 

````js
		lengthOfTime: {
			months: 6,
			interval: 6,
			startDate: moment().subtract('months', 1).startOf('month')
		},
````

from my original plugin call to

````js
		lengthOfTime: {
			months: 3,
			interval: 3,
			startDate: moment().subtract('months', 1).startOf('month')
		},
````

CLNDR.js does not provide an API call for destroying an instance. Is there another way to do this?

I'm appreciating every hint. 

Regards
Nico

**Comment by mikegioia** [comment]
I'm going to add a .destroy() method to the CLNDR class. This would allow the `.clndr(options)` to re-render a destroyed calendar.

Optionally, you can have the DOM cleared out too. I'm going to close this issue as it's replaced now with #187.
