### ISSUE TITLE
Select Date Range Event

### ISSUE THREAD

**Issue by bkenny** [kylestetz/CLNDR#97]
Is there any API to provide the ability for the user to select a date range and fire an event?

**Comment by mikegioia** [comment]
I have to agree here, I don't think adding click/drag to select multiple dates is worth the effort. It should be up to the end-user to define the click behavior for something like multi-selection.

The best thing I could see being incorporated into CLNDR would be to have an option like `allowMultiSelection` or something, where CLNDR adds classes to the days based on the user's selections. So if day 2 was selected first, then day 8, all days in between and including 2 and 8 would get a class "selected" which the user could highlight. All that would remain is triggering the date range selected event, handling "selected" class removal when another date is clicked, and then validating against invalid date ranges.

**Comment by piehouserat** [comment]
hey guys, just discovered this plugin and it's perfect for my project which requires the user to select a date range. I'm sure I could hack something together tonight but does anyone have a working example of selecting a start date and then selecting the end date?

**Comment by kylestetz** [comment]
Nope @piehouserat I don't have anything. When you make it you should share it via a JSBin or something so that future inquiries can benefit from your hard work :smile:

**Comment by mikegioia** [comment]
Closing this out as it's gone stale, but for anyone who finds this feel free to re-open it and (ideally) submit a PR. While I do think this is out-of-scope and can be managed more effectively and uniquely with the current set of event callbacks, we'd always welcome a clever/simple  solution :stuck_out_tongue:
